src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Near_Site_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Opportunity (Clinic) to which this Account is associated.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Accounts</relationshipLabel>
        <relationshipName>NearSiteAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>This field is being created to allow Lead conversion as the field requirement for Opportunity.Revenue_Type__c does not allow the creation of an Opportunity. Solutions approved by Ann Cruz.</description>
        <label>Revenue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                    <default>true</default>
                    <label>New Business</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>Is this brand new business revenue?  Under contract revenue?  Or contract renewal revenue?</description>
        <label>Revenue Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                    <default>true</default>
                    <label>New SOW</label>
                </value>
                <value>
                    <fullName>Under Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AddAccountsToNSOppControllerTest.cls
@isTest
private class AddAccountsToNSOppControllerTest {
    
     static testMethod void validate() {
        
        //Insert your mock data here
        Opportunity newOpp = new Opportunity(
        	Name='test opp 1',
        	StageName='Lead',
        	CloseDate=Date.today(),
			Revenue_Type__c = '	New Business');
        insert newOpp;
         
        Account a = new Account(Name='test acc 1');
        insert a;
         
        a.Near_Site_Opportunity__c = newOpp.Id;
         
   

        //Construct your pagereference
        PageReference testPage = new pagereference('/apex/AddAccountsToNSOpp');
        testPage.getParameters().put('id', 'newOpp1.id');
        testPage.getParameters().put('accountName', '');
        Test.setCurrentPage(testPage);
        
         
        ApexPages.StandardController sc = new ApexPages.StandardController(newOpp);
        AddAccountsToNSOppController cont = new AddAccountsToNSOppController(sc);
         
        
         
        AddAccountsToNSOppController.aAccount innerCont = new AddAccountsToNSOppController.aAccount(a);
       	
		cont.accountList = null;
        cont.proccessSelected();
        cont.toggleSort();
        cont.runQuery();
        cont.runSearch();
       	
                
        
        System.assertEquals(newOpp.Id, a.Near_Site_Opportunity__c);
        System.assertEquals(newOpp.Id, cont.currentOppId);
         

         

      	
    }
}