src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <description>New Formula Field to display Account Owner - Not &quot;changeable/editable&quot;</description>
        <formula>Owner.LastName &amp; &quot;, &quot; &amp;  Owner.FirstName</formula>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RevID__c</fullName>
        <externalId>true</externalId>
        <label>RevID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Clinic</fullName>
        <active>true</active>
        <description>Physical location for placing a clinic. Used for Near-Site Opportunities</description>
        <label>Clinic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <description>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</description>
        <inlineHelpText>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</inlineHelpText>
        <label>Budget Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic__c.object
<CustomObject>
    <description>This object will store available Clinics available for selection on Patient Referrals.</description>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <label>Clinic</label>
    <nameField>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <label>Budget Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clinic_Name__c</fullName>
        <formula>TEXT(Clinic__r.Clinic__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clinic Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <referenceTo>Clinic__c</referenceTo>
        <relationshipLabel>Clinic Budgets</relationshipLabel>
        <relationshipName>Clinic_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clinic Budget</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinic Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinic Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Period__c</fullName>
        <label>Accounting Period</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RevId__c</fullName>
        <label>Rev Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Product__c</fullName>
        <label>Salesforce Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GSP_SC_trgInvoiceLineMethods.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, 22 Jul 2020
 */
public with sharing class GSP_SC_trgInvoiceLineMethods
{
	public static void LinkInvoicelineBudgets(Set<Id> invoiceLineSet)
	{
		Set<String> revIdSet = new Set<String>(),
			clinicNameSet = new Set<String>();
		Set<Integer> monthSet = new Set<Integer>(),
			yearSet = new Set<Integer>();
		Set<Id> accountOwnerSet = new Set<Id>(),
			budgetSet = new Set<Id>(),
			productSet = new Set<Id>(),
			clinicBudgetSet = new Set<Id>();
		List<Invoice_Line__c> invoiceLinesNotMatchedByAccount = new List<Invoice_Line__c>();
		Map<Id, Invoice_Line__c> invoiceLineCacheMap = new Map<Id, Invoice_Line__c>();
		Map<String, Id> revIdKeyedAccountOwnerSet = new Map<String, Id>();
		Map<String, Id> revIdKeyedAccountSet = new Map<String, Id>();
		// Map RevId -> Product -> Budget Year - Budget-Month
		Map<String, Map<Id, Map<Integer, Map<Integer, Budget__c>>>> budgetSearchMap = new Map<String, Map<Id, Map<Integer, Map<Integer, Budget__c>>>>();
		// Map Account Owner -> Product -> Budget Year - Budget-Month
		Map<Id, Map<Id, Map<Integer, Map<Integer, Budget__c>>>> budgetOwnerSearchMap = new Map<Id, Map<Id, Map<Integer, Map<Integer, Budget__c>>>>();
		// Map -> Clinic Name -> Year -> Month
		Map<String, Map<Integer, Map<Integer, Clinic_Budget__c>>> clinicBudgetSearchMap = new Map<String, Map<Integer, Map<Integer, Clinic_Budget__c>>>();
		
		List<Invoice_Line__c> invoiceLineList = new List<Invoice_Line__c>([
			SELECT
				Id,
				RevId__c,
				Accounting_Period__c,
				Budget__c,
				Clinic__c,
				Product__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet]);
		
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			if (!String.isEmpty(invoiceLine.RevId__c) &&
				invoiceLine.Accounting_Period__c != null &&
				invoiceLine.Product__c != null)
			{
				revIdSet.add(invoiceLine.RevId__c);
				monthSet.add(invoiceLine.Accounting_Period__c.month());
				yearSet.add(invoiceLine.Accounting_Period__c.year());
				productSet.add(invoiceLine.Product__c);
				if (invoiceLine.Clinic__c != null)
				{
					clinicNameSet.add(invoiceLine.Clinic__c);
				}
			}
			else
			{
				invoiceLine.addError('No Account RevId, Accounting Period or Product to process.');
				return;
			}
		}
		
		for (Account account : [
			SELECT
				Id,
				OwnerId,
				RevId__c, (
				SELECT
					Id,
					Budget_Date__c,
					Product__c
				FROM
					Budgets__r
				WHERE
					CALENDAR_YEAR(Budget_Date__c) IN :yearSet
				AND
					CALENDAR_MONTH(Budget_Date__c) IN :monthSet
				AND
					Product__c IN :productSet)
			FROM
				Account
			WHERE
				RevId__c IN :revIdSet])
		{
			revIdKeyedAccountOwnerSet.put(account.RevId__c, account.OwnerId);
			revIdKeyedAccountSet.put(account.RevId__c, account.Id);
			if (!budgetSearchMap.containsKey(account.RevId__c))
			{
				budgetSearchMap.put(account.RevId__c, new Map<Id, Map<Integer, Map<Integer, Budget__c>>>());
			}
			for (Budget__c budget : account.Budgets__r)
			{
				if (!budgetSearchMap.get(account.RevId__c).containsKey(budget.Product__c))
				{
					budgetSearchMap.get(account.RevId__c).put(budget.Product__c, new Map<Integer, Map<Integer, Budget__c>>());
				}
				if (!budgetSearchMap.get(account.RevId__c).get(budget.Product__c).containsKey(budget.Budget_Date__c.year()))
				{
					budgetSearchMap.get(account.RevId__c).get(budget.Product__c).put(budget.Budget_Date__c.year(), new Map<Integer, Budget__c>());
				}
				budgetSearchMap.get(account.RevId__c).get(budget.Product__c).get(budget.Budget_Date__c.year()).put(budget.Budget_Date__c.month(), budget);
			}	
		}
		
		for (Clinic_Budget__c clinicBudget : [
			SELECT
				Id,
				Budget_Date__c,
				Clinic_Name__c
			FROM
				Clinic_Budget__c
			WHERE
				CALENDAR_YEAR(Budget_Date__c) IN :yearSet
			AND
				CALENDAR_MONTH(Budget_Date__c) IN :monthSet
			AND
				Clinic_name__c IN :clinicNameSet])
		{
			if (!clinicBudgetSearchMap.containsKey(clinicBudget.Clinic_Name__c))
			{
				clinicBudgetSearchMap.put(clinicBudget.Clinic_Name__c, new Map<Integer, Map<Integer, Clinic_Budget__c>>());
			}
			if (!clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).containsKey(clinicBudget.Budget_Date__c.year()))
			{
				clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).put(clinicBudget.Budget_Date__c.year(), new Map<Integer, Clinic_Budget__c>());
			}
			clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).get(clinicBudget.Budget_Date__c.year()).put(clinicBudget.Budget_Date__c.month(), clinicBudget);
		}
		
		monthSet.clear();
		yearSet.clear();
		productSet.clear();
		// Added debug statements for inevitable typos.
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			invoiceLine.Account__c = revIdKeyedAccountSet.get(invoiceLine.RevId__c);
			invoiceLineCacheMap.put(invoiceLine.Id, invoiceLine);
			if (invoiceLine.Budget__c != null)
			{
				budgetSet.add(invoiceLine.Budget__c);
			}
			Boolean bFound = false;
			System.debug('Match Account');
			if (budgetSearchMap.containsKey(invoiceLine.RevId__c))
			{System.debug('MA Key 1');
				if (budgetSearchMap.get(invoiceLine.RevId__c).containsKey(invoiceLine.Product__c))
				{System.debug('MA Key 2');
					if (budgetSearchMap.get(invoiceLine.RevId__c).get(invoiceLine.Product__c).
						containsKey(invoiceLine.Accounting_Period__c.year()))
					{System.debug('MA Key 3');
						if (budgetSearchMap.get(invoiceLine.RevId__c).get(invoiceLine.Product__c).
							get(invoiceLine.Accounting_Period__c.year()).containsKey(invoiceLine.Accounting_Period__c.month()))
						{System.debug('MA Key 4');
							Id budgetId = budgetSearchMap.get(invoiceLine.RevId__c).get(invoiceLine.Product__c).
								get(invoiceLine.Accounting_Period__c.year()).get(invoiceLine.Accounting_Period__c.month()).Id;
							invoiceLine.Budget__c = budgetId;
							budgetSet.add(invoiceLine.Budget__c);
							bFound = true;
						}
					}
				}
			}
			if (!bFound)
			{
				invoiceLinesNotMatchedByAccount.add(invoiceLine);
				if (revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c) != null)
				{
					accountOwnerSet.add(revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c));
					monthSet.add(invoiceLine.Accounting_Period__c.month());
					yearSet.add(invoiceLine.Accounting_Period__c.year());
					productSet.add(invoiceLine.Product__c);
				}
			}
			
			if (invoiceLine.Clinic__c != null)
			{
				if (clinicBudgetSearchMap.containsKey(invoiceLine.Clinic__c))
				{
					if (clinicBudgetSearchMap.get(invoiceLine.Clinic__c).containsKey(invoiceLine.Accounting_Period__c.year()))
					{System.debug('INV: ' + invoiceLine + ' - ' + clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceLine.Accounting_Period__c.year()));
						if (clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceLine.Accounting_Period__c.year()).
							containsKey(invoiceLine.Accounting_Period__c.month()))
						{
							Id clinicBudgetId = clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceLine.Accounting_Period__c.year()).
								get(invoiceLine.Accounting_Period__c.month()).Id;
							invoiceLine.Clinic_Budget__c = clinicBudgetId;
							clinicBudgetSet.add(clinicBudgetId);
						}
					}
				}
			}
		}
		
		if (!accountOwnerSet.isEmpty())
		{
			for (Budget__c budget : [
				SELECT
					Id,
					Name,
					Account_Owner__c,
					Budget_Date__c,
					Product__c
				FROM
					Budget__c
				WHERE
					Account_Owner__c IN :accountOwnerSet
				AND
					CALENDAR_YEAR(Budget_Date__c) IN :yearSet
				AND
					CALENDAR_MONTH(Budget_Date__c) IN :monthSet
				AND
					Product__c IN :productSet
				AND
					Account_Owner__c != null])
			{
				System.debug(budget.Name + ' : ' + budget.Account_Owner__c);
				if (!budgetOwnerSearchMap.containsKey(budget.Account_Owner__c))
				{
					budgetOwnerSearchMap.put(budget.Account_Owner__c, new Map<Id, Map<Integer, Map<Integer, Budget__c>>>());
				}
				if (!budgetOwnerSearchMap.get(budget.Account_Owner__c).containsKey(budget.Product__c))
				{
					budgetOwnerSearchMap.get(budget.Account_Owner__c).put(budget.Product__c, new Map<Integer, Map<Integer, Budget__c>>());
				}
				if (!budgetOwnerSearchMap.get(budget.Account_Owner__c).get(budget.Product__c).
					containsKey(budget.Budget_Date__c.year()))
				{
					budgetOwnerSearchMap.get(budget.Account_Owner__c).get(budget.Product__c).
						put(budget.Budget_Date__c.year(), new Map<Integer, Budget__c>());
				}
				budgetOwnerSearchMap.get(budget.Account_Owner__c).get(budget.Product__c).
					get(budget.Budget_Date__c.year()).put(budget.Budget_Date__c.month(), budget);
			}
			
			for (Invoice_Line__c invoiceLine : invoiceLinesNotMatchedByAccount)
			{
				Boolean bFound = false;
				System.debug('Match Owner');
				if (budgetOwnerSearchMap.containsKey(revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c)))
				{System.debug('MO Key 1');
					if (budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c)).containsKey(invoiceLine.Product__c))
					{System.debug('MO Key 2');
						if (budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c)).get(invoiceLine.Product__c).
							containsKey(invoiceLine.Accounting_Period__c.year()))
						{System.debug('MO Key 3');
							if (budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c)).get(invoiceLine.Product__c).
								get(invoiceLine.Accounting_Period__c.year()).containsKey(invoiceLine.Accounting_Period__c.month()))
							{System.debug('MO Key 4');
								Id budgetId = budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.RevId__c)).get(invoiceLine.Product__c).
									get(invoiceLine.Accounting_Period__c.year()).get(invoiceLine.Accounting_Period__c.month()).Id;
								invoiceLine.Budget__c = budgetId;
								budgetSet.add(invoiceLine.Budget__c);
								invoiceLineCacheMap.put(invoiceLine.Id, invoiceLine);
								bFound = true;
							}
						}
					}
				}
				if (!bFound)
				{
					
				}
			}
		}
		if (!invoiceLineCacheMap.isEmpty())
		{
			update invoiceLineCacheMap.values();
		}
		if (!budgetSet.isEmpty())
		{
			GSP_SC_BudgetHelper.RollUpInvoiceValues(budgetSet);
		}
		if (!clinicBudgetSet.isEmpty())
		{
			GSP_SC_ClinicBudgetHelper.RollUpClinicBudgets(clinicBudgetSet);
		}
	}
	
	public static void LinkInvoicelineBudgetsByAccountName(Set<Id> invoiceLineSet)
	{
		Set<String> accountNameSet = new Set<String>(),
			clinicNameSet = new Set<String>();
		Set<Integer> monthSet = new Set<Integer>(),
			yearSet = new Set<Integer>();
		Set<Id> accountOwnerSet = new Set<Id>(),
			budgetSet = new Set<Id>(),
			productSet = new Set<Id>(),
			clinicBudgetSet = new Set<Id>();
		List<Invoice_Line__c> invoiceLinesNotMatchedByAccount = new List<Invoice_Line__c>();
		Map<Id, Invoice_Line__c> invoiceLineCacheMap = new Map<Id, Invoice_Line__c>();
		Map<String, Id> revIdKeyedAccountOwnerSet = new Map<String, Id>();
		Map<String, Id> revIdKeyedAccountSet = new Map<String, Id>();
		// Map RevId -> Product -> Budget Year - Budget-Month
		Map<String, Map<Id, Map<Integer, Map<Integer, Budget__c>>>> budgetSearchMap = new Map<String, Map<Id, Map<Integer, Map<Integer, Budget__c>>>>();
		// Map Account Owner -> Product -> Budget Year - Budget-Month
		Map<Id, Map<Id, Map<Integer, Map<Integer, Budget__c>>>> budgetOwnerSearchMap = new Map<Id, Map<Id, Map<Integer, Map<Integer, Budget__c>>>>();
		// Map -> Clinic Name -> Year -> Month
		Map<String, Map<Integer, Map<Integer, Clinic_Budget__c>>> clinicBudgetSearchMap = new Map<String, Map<Integer, Map<Integer, Clinic_Budget__c>>>();
		
		List<Invoice_Line__c> invoiceLineList = new List<Invoice_Line__c>([
			SELECT
				Id,
				Account_Name__c,
				Accounting_Period__c,
				Budget__c,
				Product__c,
				Clinic__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet]);
		
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			if (!String.isEmpty(invoiceLine.Account_Name__c) &&
				invoiceLine.Accounting_Period__c != null &&
				invoiceLine.Product__c != null)
			{
				accountNameSet.add(invoiceLine.Account_Name__c);
				monthSet.add(invoiceLine.Accounting_Period__c.month());
				yearSet.add(invoiceLine.Accounting_Period__c.year());
				productSet.add(invoiceLine.Product__c);
				if (invoiceLine.Clinic__c != null)
				{
					clinicNameSet.add(invoiceLine.Clinic__c);
				}
			}
			else
			{
				invoiceLine.addError('No Account Name, Accounting Period or Product to process.');
				return;
			}
		}
		
		for (Account account : [
			SELECT
				Id,
				OwnerId,
				Name, (
				SELECT
					Id,
					Budget_Date__c,
					Product__c
				FROM
					Budgets__r
				WHERE
					CALENDAR_YEAR(Budget_Date__c) IN :yearSet
				AND
					CALENDAR_MONTH(Budget_Date__c) IN :monthSet
				AND
					Product__c IN :productSet)
			FROM
				Account
			WHERE
				Name IN :accountNameSet])
		{
			revIdKeyedAccountOwnerSet.put(account.Name, account.OwnerId);
			revIdKeyedAccountSet.put(account.Name, account.Id);
			if (!budgetSearchMap.containsKey(account.Name))
			{
				budgetSearchMap.put(account.Name, new Map<Id, Map<Integer, Map<Integer, Budget__c>>>());
			}
			for (Budget__c budget : account.Budgets__r)
			{
				if (!budgetSearchMap.get(account.Name).containsKey(budget.Product__c))
				{
					budgetSearchMap.get(account.Name).put(budget.Product__c, new Map<Integer, Map<Integer, Budget__c>>());
				}
				if (!budgetSearchMap.get(account.Name).get(budget.Product__c).containsKey(budget.Budget_Date__c.year()))
				{
					budgetSearchMap.get(account.Name).get(budget.Product__c).put(budget.Budget_Date__c.year(), new Map<Integer, Budget__c>());
				}
				budgetSearchMap.get(account.Name).get(budget.Product__c).get(budget.Budget_Date__c.year()).put(budget.Budget_Date__c.month(), budget);
			}	
		}
		
		for (Clinic_Budget__c clinicBudget : [
			SELECT
				Id,
				Budget_Date__c,
				Clinic_Name__c
			FROM
				Clinic_Budget__c
			WHERE
				CALENDAR_YEAR(Budget_Date__c) IN :yearSet
			AND
				CALENDAR_MONTH(Budget_Date__c) IN :monthSet
			AND
				Clinic_name__c IN :clinicNameSet])
		{
			if (!clinicBudgetSearchMap.containsKey(clinicBudget.Clinic_Name__c))
			{
				clinicBudgetSearchMap.put(clinicBudget.Clinic_Name__c, new Map<Integer, Map<Integer, Clinic_Budget__c>>());
			}
			if (!clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).containsKey(clinicBudget.Budget_Date__c.year()))
			{
				clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).put(clinicBudget.Budget_Date__c.year(), new Map<Integer, Clinic_Budget__c>());
			}
			clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).get(clinicBudget.Budget_Date__c.year()).put(clinicBudget.Budget_Date__c.month(), clinicBudget);
		}
		
		monthSet.clear();
		yearSet.clear();
		productSet.clear();
		// Added debug statements for inevitable typos.
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			invoiceLine.Account__c = revIdKeyedAccountSet.get(invoiceLine.Account_Name__c);
			invoiceLineCacheMap.put(invoiceLine.Id, invoiceLine);
			if (invoiceLine.Budget__c != null)
			{
				budgetSet.add(invoiceLine.Budget__c);
			}
			Boolean bFound = false;
			System.debug('Match Account');
			if (budgetSearchMap.containsKey(invoiceLine.Account_Name__c))
			{System.debug('MA Key 1');
				if (budgetSearchMap.get(invoiceLine.Account_Name__c).containsKey(invoiceLine.Product__c))
				{System.debug('MA Key 2');
					if (budgetSearchMap.get(invoiceLine.Account_Name__c).get(invoiceLine.Product__c).
						containsKey(invoiceLine.Accounting_Period__c.year()))
					{System.debug('MA Key 3');
						if (budgetSearchMap.get(invoiceLine.Account_Name__c).get(invoiceLine.Product__c).
							get(invoiceLine.Accounting_Period__c.year()).containsKey(invoiceLine.Accounting_Period__c.month()))
						{System.debug('MA Key 4');
							Id budgetId = budgetSearchMap.get(invoiceLine.Account_Name__c).get(invoiceLine.Product__c).
								get(invoiceLine.Accounting_Period__c.year()).get(invoiceLine.Accounting_Period__c.month()).Id;
							invoiceLine.Budget__c = budgetId;
							budgetSet.add(invoiceLine.Budget__c);
							bFound = true;
						}
					}
				}
			}
			if (!bFound)
			{
				invoiceLinesNotMatchedByAccount.add(invoiceLine);
				if (revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c) != null)
				{
					accountOwnerSet.add(revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c));
					monthSet.add(invoiceLine.Accounting_Period__c.month());
					yearSet.add(invoiceLine.Accounting_Period__c.year());
					productSet.add(invoiceLine.Product__c);
				}
			}
			if (invoiceLine.Clinic__c != null)
			{
				if (clinicBudgetSearchMap.containsKey(invoiceLine.Clinic__c))
				{
					if (clinicBudgetSearchMap.get(invoiceLine.Clinic__c).containsKey(invoiceLine.Accounting_Period__c.year()))
					{
						if (clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceLine.Accounting_Period__c.year()).
							containsKey(invoiceLine.Accounting_Period__c.month()))
						{
							Id clinicBudgetId = clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceLine.Accounting_Period__c.year()).
								get(invoiceLine.Accounting_Period__c.month()).Id;
							invoiceLine.Clinic_Budget__c = clinicBudgetId;
							clinicBudgetSet.add(clinicBudgetId);
						}
					}
				}
			}
		}
		
		if (!accountOwnerSet.isEmpty())
		{
			for (Budget__c budget : [
				SELECT
					Id,
					Name,
					Account_Owner__c,
					Budget_Date__c,
					Product__c
				FROM
					Budget__c
				WHERE
					Account_Owner__c IN :accountOwnerSet
				AND
					CALENDAR_YEAR(Budget_Date__c) IN :yearSet
				AND
					CALENDAR_MONTH(Budget_Date__c) IN :monthSet
				AND
					Product__c IN :productSet
				AND
					Account_Owner__c != null])
			{
				System.debug(budget.Name + ' : ' + budget.Account_Owner__c);
				if (!budgetOwnerSearchMap.containsKey(budget.Account_Owner__c))
				{
					budgetOwnerSearchMap.put(budget.Account_Owner__c, new Map<Id, Map<Integer, Map<Integer, Budget__c>>>());
				}
				if (!budgetOwnerSearchMap.get(budget.Account_Owner__c).containsKey(budget.Product__c))
				{
					budgetOwnerSearchMap.get(budget.Account_Owner__c).put(budget.Product__c, new Map<Integer, Map<Integer, Budget__c>>());
				}
				if (!budgetOwnerSearchMap.get(budget.Account_Owner__c).get(budget.Product__c).
					containsKey(budget.Budget_Date__c.year()))
				{
					budgetOwnerSearchMap.get(budget.Account_Owner__c).get(budget.Product__c).
						put(budget.Budget_Date__c.year(), new Map<Integer, Budget__c>());
				}
				budgetOwnerSearchMap.get(budget.Account_Owner__c).get(budget.Product__c).
					get(budget.Budget_Date__c.year()).put(budget.Budget_Date__c.month(), budget);
			}
			
			for (Invoice_Line__c invoiceLine : invoiceLinesNotMatchedByAccount)
			{
				Boolean bFound = false;
				System.debug('Match Owner');
				if (budgetOwnerSearchMap.containsKey(revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c)))
				{System.debug('MO Key 1');
					if (budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c)).containsKey(invoiceLine.Product__c))
					{System.debug('MO Key 2');
						if (budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c)).get(invoiceLine.Product__c).
							containsKey(invoiceLine.Accounting_Period__c.year()))
						{System.debug('MO Key 3');
							if (budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c)).get(invoiceLine.Product__c).
								get(invoiceLine.Accounting_Period__c.year()).containsKey(invoiceLine.Accounting_Period__c.month()))
							{System.debug('MO Key 4');
								Id budgetId = budgetOwnerSearchMap.get(revIdKeyedAccountOwnerSet.get(invoiceLine.Account_Name__c)).get(invoiceLine.Product__c).
									get(invoiceLine.Accounting_Period__c.year()).get(invoiceLine.Accounting_Period__c.month()).Id;
								invoiceLine.Budget__c = budgetId;
								budgetSet.add(invoiceLine.Budget__c);
								invoiceLineCacheMap.put(invoiceLine.Id, invoiceLine);
								bFound = true;
							}
						}
					}
				}
				if (!bFound)
				{
					
				}
			}
		}
		if (!invoiceLineCacheMap.isEmpty())
		{
			update invoiceLineCacheMap.values();
		}
		if (!budgetSet.isEmpty())
		{
			GSP_SC_BudgetHelper.RollUpInvoiceValues(budgetSet);
		}
		if (!clinicBudgetSet.isEmpty())
		{
			GSP_SC_ClinicBudgetHelper.RollUpClinicBudgets(clinicBudgetSet);
		}
	}
	
	public static void RollUpBudgets(List<Invoice_Line__c> invoiceLineList)
	{
		Set<Id> budgetSet = new Set<Id>();
		Set<Id> clinicBudgetSet = new Set<Id>();
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			if (invoiceLine.Budget__c != null)
			{
				budgetSet.add(invoiceLine.Budget__c);
			}
			if (invoiceLine.Clinic_Budget__c != null)
			{
				clinicBudgetSet.add(invoiceLine.Clinic_Budget__c);
			}
		}
		if (!budgetSet.isEmpty())
		{
			GSP_SC_BudgetHelper.RollUpInvoiceValues(budgetSet);
		}
		if (!clinicBudgetSet.isEmpty())
		{
			GSP_SC_ClinicBudgetHelper.RollUpClinicBudgets(clinicBudgetSet);
		}
	}
	
	public static void LinkInvoiceLineProducts(List<Invoice_Line__c> invoiceLineList)
	{
		Map<String, List<Invoice_Line__c>> productCodeKeyedInvoiceMap = new Map<String, List<Invoice_Line__c>>();
		Set<String> productCodeSet = new Set<String>();
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			if (invoiceLine.Salesforce_Product__c != null)
			{
				if (!productCodeKeyedInvoiceMap.containsKey(invoiceLine.Salesforce_Product__c))
				{
					productCodeKeyedInvoiceMap.put(invoiceLine.Salesforce_Product__c, new List<Invoice_Line__c>());
				}
				productCodeKeyedInvoiceMap.get(invoiceLine.Salesforce_Product__c).add(invoiceLine);
			}
		}
		
		for (Product2 product : [
			SELECT
				Id,
				ProductCode
			FROM
				Product2
			WHERE
				ProductCode IN :productCodeKeyedInvoiceMap.keySet()])
		{
			productCodeSet.add(product.ProductCode);
			for (Invoice_Line__c invoiceLine : productCodeKeyedInvoiceMap.get(product.ProductCode))
			{
				invoiceLine.Product__c = product.Id;
			}
		}
		
		for (String strKey : productCodeKeyedInvoiceMap.keySet())
		{
			if (!productCodeSet.contains(strKey))
			{
				System.debug('Product search on InvoiceLine failed for ' + strKey);
			}
		}
	}
}