src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <description>New Formula Field to display Account Owner - Not &quot;changeable/editable&quot;</description>
        <formula>Owner.LastName &amp; &quot;, &quot; &amp;  Owner.FirstName</formula>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Used during data migration from old Opportunity. For information only until this field can be removed.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RevID__c</fullName>
        <externalId>true</externalId>
        <label>RevID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Clinic</fullName>
        <active>true</active>
        <description>Physical location for placing a clinic. Used for Near-Site Opportunities</description>
        <label>Clinic</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <description>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</description>
        <inlineHelpText>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</inlineHelpText>
        <label>Budget Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Total_Amount__c</fullName>
        <label>Invoice Total Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic__c.object
<CustomObject>
    <description>This object will store available Clinics available for selection on Patient Referrals.</description>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <label>Clinic</label>
    <nameField>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <label>Budget Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <referenceTo>Clinic__c</referenceTo>
        <relationshipLabel>Clinic Budgets</relationshipLabel>
        <relationshipName>Clinic_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clinic Budget</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinic Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinic Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Period__c</fullName>
        <label>Accounting Period</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RevId__c</fullName>
        <label>Rev Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salesforce_Product__c</fullName>
        <label>Salesforce Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IMPORTANT: One Setting with the Name set to &apos;Default&apos;</description>
    <fields>
        <fullName>Global_Schedule_Interval__c</fullName>
        <description>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1</description>
        <inlineHelpText>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1</inlineHelpText>
        <label>Global Schedule Interval</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Schedule Settings</label>
</CustomObject>

src/classes/GSP_SC_trgInvoicelineMethods_TEST.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, 22 Jul 2020
 */
@isTest
private class GSP_SC_trgInvoicelineMethods_TEST
{
	@isTest
	private static void test_LinkInvoicelineBudgets_Account()
	{
		Integer PRODUCT_CHUNK = 3;
		String CLINIC_NAME = 'AMP Austin';
		Set<Id> budgetSet = new Set<Id>();
		Set<Id> invoiceLineSet = new Set<Id>();
		List<String> productCodeList = new List<String>{ '12345', '17226', '27366' };
		List<Budget__c> budgetCache = new List<Budget__c>();
		List<Product2> productCache = new List<Product2>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
		List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
		Pricebook2 pricebook, standardPricebook;
		Integer i, j;
		
		List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
		if (!scheduleSettings.isEmpty())
		{
			for (Schedule_Settings__c scheduleSetting : scheduleSettings)
			{
				scheduleSetting.Global_Schedule_Interval__c = 'M1';
			}
			update scheduleSettings;
		}
		else
		{
			Schedule_Settings__c setting = new Schedule_Settings__c(
				Name = 'Default',
				Global_Schedule_Interval__c = 'M1');
			insert setting;
			System.assertNotEquals(setting.Id, null);
		}
		
		for (Pricebook2 pricebook2 : [
			SELECT
				Id,
				IsStandard,
				IsActive
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			OR
				IsActive = true])
		{
			if (pricebook2.isStandard)
			{
				standardPricebook = pricebook2;
			}
			if (pricebook2.isActive)
			{
				pricebook = pricebook2;
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
					break;
				}
			}
		}
		
		for (i = 0; i < PRODUCT_CHUNK; i++)
		{
			Product2 product = new Product2(
				Name = 'Product ' + i,
				IsActive = true,
				ProductCode = productCodeList.get(i));
			productCache.add(product);
		}
		insert productCache;

		Account account = new Account(
			Name = 'Apex Test Account',
			RevId__c = 'testAccount');
		insert account;
		System.assertNotEquals(account.Id, null);
		
		Date dtBudget = Date.today().addYears(10).toStartOfMonth();
		for (i = 0; i < 12; i++)
		{
			for (Product2 product : productCache)
			{
				Budget__c budget = new Budget__c(
					Budget_Date__c = dtBudget.addMonths(i),
					Account__c = account.Id,
					Product__c = product.Id);
				budgetCache.add(budget);
			}
		}
		insert budgetCache;
		for (Budget__c budget : budgetCache)
		{
			budgetSet.add(budget.Id);
		}
		
		Clinic__c clinic = new Clinic__c(
			Name = 'Apex Test Clinic',
			Clinic__c = CLINIC_NAME);
		insert clinic;
		System.assertNotEquals(clinic.Id, null);
		
		Clinic_Budget__c clinicBudget = new Clinic_Budget__c(
			Clinic__c = clinic.Id,
			Budget_date__c = Date.today().addYears(10).toStartOfMonth());
		insert clinicBudget;
		System.assertNotEquals(clinicBudget.Id, null);
			
		
		for (Product2 product : productCache)
		{
			Invoice_Line__c invoiceLine = new Invoice_Line__c(
				RevId__c = account.RevId__c,
				Accounting_Period__c = Date.today().addYears(10),
				Amount__c = 12000,
				Salesforce_Product__c = product.productCode,
				Clinic__c = CLINIC_NAME);
			invoiceLineCache.add(invoiceLine);
		}
		insert invoiceLineCache;
		
		for (Invoice_Line__c invoiceLine : invoiceLineCache)
		{
			invoiceLineSet.add(invoiceLine.Id);
		}
		
		for (Invoice_Line__c testInvoiceLine : [
			SELECT
				Budget__c,
				RevId__c,
				Account__c,
				Accounting_Period__c,
				Clinic_Budget__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet])
		{
			System.assertEquals(true, budgetSet.contains(testInvoiceLine.Budget__c));
			System.assertNotEquals(null, testInvoiceLine.Clinic_Budget__c);
		}
	}
	
	@isTest
	private static void test_LinkInvoicelineBudgets_AccountName()
	{
		Integer PRODUCT_CHUNK = 3;
		String CLINIC_NAME = 'AMP Austin';
		Set<Id> budgetSet = new Set<Id>();
		Set<Id> invoiceLineSet = new Set<Id>();
		List<String> productCodeList = new List<String>{ '12345', '17226', '27366' };
		List<Budget__c> budgetCache = new List<Budget__c>();
		List<Product2> productCache = new List<Product2>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
		List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
		Pricebook2 pricebook, standardPricebook;
		Integer i, j;
		
		List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
		if (!scheduleSettings.isEmpty())
		{
			for (Schedule_Settings__c scheduleSetting : scheduleSettings)
			{
				scheduleSetting.Global_Schedule_Interval__c = 'M1';
			}
			update scheduleSettings;
		}
		else
		{
			Schedule_Settings__c setting = new Schedule_Settings__c(
				Name = 'Default',
				Global_Schedule_Interval__c = 'M1');
			insert setting;
			System.assertNotEquals(setting.Id, null);
		}
		
		for (Pricebook2 pricebook2 : [
			SELECT
				Id,
				IsStandard,
				IsActive
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			OR
				IsActive = true])
		{
			if (pricebook2.isStandard)
			{
				standardPricebook = pricebook2;
			}
			if (pricebook2.isActive)
			{
				pricebook = pricebook2;
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
					break;
				}
			}
		}
		
		for (i = 0; i < PRODUCT_CHUNK; i++)
		{
			Product2 product = new Product2(
				Name = 'Product ' + i,
				IsActive = true,
				ProductCode = productCodeList.get(i));
			productCache.add(product);
		}
		insert productCache;

		Account account = new Account(
			Name = 'Apex Test Account',
			RevId__c = 'testAccount');
		insert account;
		System.assertNotEquals(account.Id, null);
		
		Date dtBudget = Date.today().addYears(10).toStartOfMonth();
		for (i = 0; i < 12; i++)
		{
			for (Product2 product : productCache)
			{
				Budget__c budget = new Budget__c(
					Budget_Date__c = dtBudget.addMonths(i),
					Account__c = account.Id,
					Product__c = product.Id);
				budgetCache.add(budget);
			}
		}
		insert budgetCache;
		for (Budget__c budget : budgetCache)
		{
			budgetSet.add(budget.Id);
		}
		
		Clinic__c clinic = new Clinic__c(
			Name = 'Apex Test Clinic',
			Clinic__c = CLINIC_NAME);
		insert clinic;
		System.assertNotEquals(clinic.Id, null);
		
		Clinic_Budget__c clinicBudget = new Clinic_Budget__c(
			Clinic__c = clinic.Id,
			Budget_date__c = Date.today().addYears(10).toStartOfMonth());
		insert clinicBudget;
		System.assertNotEquals(clinicBudget.Id, null);
		
		for (Product2 product : productCache)
		{
			Invoice_Line__c invoiceLine = new Invoice_Line__c(
				Account_Name__c = account.Name,
				Accounting_Period__c = Date.today().addYears(10),
				Amount__c = 12000,
				Salesforce_Product__c = product.productCode,
				Clinic__c = CLINIC_NAME);
			invoiceLineCache.add(invoiceLine);
		}
		insert invoiceLineCache;
		
		for (Invoice_Line__c invoiceLine : invoiceLineCache)
		{
			invoiceLineSet.add(invoiceLine.Id);
		}
		
		for (Invoice_Line__c testInvoiceLine : [
			SELECT
				Budget__c,
				RevId__c,
				Account__c,
				Accounting_Period__c,
				Clinic_Budget__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet])
		{
			System.assertEquals(true, budgetSet.contains(testInvoiceLine.Budget__c));
			System.assertNotEquals(null, testInvoiceLine.Clinic_Budget__c);
		}
	}
	
	@isTest
	private static void test_LinkInvoicelineBudgets_Owner()
	{
		Integer PRODUCT_CHUNK = 3;
		Set<Id> budgetSet = new set<Id>();
		Set<Id> invoiceLineSet = new Set<Id>();
		List<String> productCodeList = new List<String>{ '12345', '17226', '27366' };
		List<Budget__c> budgetCache = new List<Budget__c>();
		List<Product2> productCache = new List<Product2>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
		List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
		Pricebook2 pricebook, standardPricebook;
		Integer i, j;
		
		List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
		if (!scheduleSettings.isEmpty())
		{
			for (Schedule_Settings__c scheduleSetting : scheduleSettings)
			{
				scheduleSetting.Global_Schedule_Interval__c = 'M1';
			}
			update scheduleSettings;
		}
		else
		{
			Schedule_Settings__c setting = new Schedule_Settings__c(
				Name = 'Default',
				Global_Schedule_Interval__c = 'M1');
			insert setting;
			System.assertNotEquals(setting.Id, null);
		}
		
		for (Pricebook2 pricebook2 : [
			SELECT
				Id,
				IsStandard,
				IsActive
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			OR
				IsActive = true])
		{
			if (pricebook2.isStandard)
			{
				standardPricebook = pricebook2;
			}
			if (pricebook2.isActive)
			{
				pricebook = pricebook2;
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
					break;
				}
			}
		}
		
		for (i = 0; i < PRODUCT_CHUNK; i++)
		{
			Product2 product = new Product2(
				Name = 'Product ' + i,
				IsActive = true,
				ProductCode = productCodeList.get(i));
			productCache.add(product);
		}
		insert productCache;

		Account account = new Account(
			Name = 'Apex Test Account',
			RevId__c = 'testAccount');
		insert account;
		System.assertNotEquals(account.Id, null);
		
		Date dtBudget = Date.today().addYears(10).toStartOfMonth();
		for (i = 0; i < 12; i++)
		{
			for (Product2 product : productCache)
			{
				Budget__c budget = new Budget__c(
					Budget_Date__c = dtBudget.addMonths(i),
					Account_Owner__c = userInfo.getUserId(),
					Product__c = product.Id);
				budgetCache.add(budget);
			}
		}
		insert budgetCache;
		for (Budget__c budget : budgetCache)
		{
			budgetSet.add(budget.Id);
		}
		
		for (Product2 product : productCache)
		{
			Invoice_Line__c invoiceLine = new Invoice_Line__c(
				RevId__c = account.RevId__c,
				Accounting_Period__c = Date.today().addYears(10),
				Amount__c = 12000,
				Salesforce_Product__c = product.productCode);
			invoiceLineCache.add(invoiceLine);
		}
		insert invoiceLineCache;
		
		for (Invoice_Line__c invoiceLine : invoiceLineCache)
		{
			invoiceLineSet.add(invoiceLine.Id);
		}
		
		for (Invoice_Line__c testInvoiceLine : [
			SELECT
				Budget__c,
				RevId__c,
				Account__c,
				Accounting_Period__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet])
		{
			System.assertEquals(true, budgetSet.contains(testInvoiceLine.Budget__c));
		}
	}
	
	@isTest
	private static void test_LinkInvoicelineBudgets_DateChange()
	{
		Integer PRODUCT_CHUNK = 3;
		Set<Id> budgetSet = new set<Id>();
		Set<Id> invoiceLineSet = new Set<Id>();
		Invoice_Line__c modifiedInvoiceLine = null;
		List<String> productCodeList = new List<String>{ '12345', '17226', '27366' };
		List<Budget__c> budgetCache = new List<Budget__c>();
		List<Product2> productCache = new List<Product2>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
		List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
		Pricebook2 pricebook, standardPricebook;
		Integer i, j;
		
		List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
		if (!scheduleSettings.isEmpty())
		{
			for (Schedule_Settings__c scheduleSetting : scheduleSettings)
			{
				scheduleSetting.Global_Schedule_Interval__c = 'M1';
			}
			update scheduleSettings;
		}
		else
		{
			Schedule_Settings__c setting = new Schedule_Settings__c(
				Name = 'Default',
				Global_Schedule_Interval__c = 'M1');
			insert setting;
			System.assertNotEquals(setting.Id, null);
		}
		
		for (Pricebook2 pricebook2 : [
			SELECT
				Id,
				IsStandard,
				IsActive
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			OR
				IsActive = true])
		{
			if (pricebook2.isStandard)
			{
				standardPricebook = pricebook2;
			}
			if (pricebook2.isActive)
			{
				pricebook = pricebook2;
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
					break;
				}
			}
		}
		
		for (i = 0; i < PRODUCT_CHUNK; i++)
		{
			Product2 product = new Product2(
				Name = 'Product ' + i,
				IsActive = true,
				ProductCode = productCodeList.get(i));
			productCache.add(product);
		}
		insert productCache;

		Account account = new Account(
			Name = 'Apex Test Account',
			RevId__c = 'testAccount');
		insert account;
		System.assertNotEquals(account.Id, null);
		
		Date dtBudget = Date.today().addYears(10).toStartOfMonth();
		for (i = 0; i < 12; i++)
		{
			for (Product2 product : productCache)
			{
				Budget__c budget = new Budget__c(
					Budget_Date__c = dtBudget.addMonths(i),
					Account__c = account.Id,
					Product__c = product.Id);
				budgetCache.add(budget);
			}
		}
		insert budgetCache;
		
		for (Budget__c budget : budgetCache)
		{
			budgetSet.add(budget.Id);
		}
		
		for (Product2 product : productCache)
		{
			Invoice_Line__c invoiceLine = new Invoice_Line__c(
				RevId__c = account.RevId__c,
				Accounting_Period__c = Date.today().addYears(10),
				Amount__c = 12000,
				Salesforce_Product__c = product.productCode);
			invoiceLineCache.add(invoiceLine);
		}
		insert invoiceLineCache;
		
		for (Invoice_Line__c invoiceLine : invoiceLineCache)
		{
			invoiceLineSet.add(invoiceLine.Id);
		}
		
		for (Invoice_Line__c testInvoiceLine : [
			SELECT
				Amount__c,
				Budget__c,
				Budget__r.Invoice_Total_Amount__c,
				RevId__c,
				Account__c,
				Accounting_Period__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet])
		{
			if (testInvoiceLine.Id == invoiceLineCache.get(0).Id)
			{
				modifiedInvoiceLine = testInvoiceLine;
			}
			System.assertEquals(true, budgetSet.contains(testInvoiceLine.Budget__c));
			System.assertEquals(testInvoiceLine.Amount__c, testInvoiceLine.Budget__r.Invoice_Total_Amount__c);
		}
		
		System.assertNotEquals(null, modifiedInvoiceLine);
		modifiedInvoiceLine.Accounting_Period__c = modifiedInvoiceLine.Accounting_Period__c.addMonths(1);
		update modifiedInvoiceLine;
		
		List<Invoice_Line__c> testInvoiceLines = new List<Invoice_Line__c>([
			SELECT
				Amount__c,
				Budget__c,
				Budget__r.Invoice_Total_Amount__c,
				RevId__c,
				Accounting_Period__c
			FROM
				Invoice_Line__c
			WHERE
				Id = :modifiedInvoiceLine.Id]);
		System.assertEquals(1, testInvoiceLines.size());
		Invoice_Line__c testInvoiceLine = testInvoiceLines.get(0);
		System.assertEquals(true, budgetSet.contains(testInvoiceLine.Budget__c));
		System.assertEquals(testInvoiceLine.Amount__c, testInvoiceLine.Budget__r.Invoice_Total_Amount__c);
		System.assertNotEquals(modifiedInvoiceLine.Budget__c, testInvoiceLine.Budget__c);
		
		List<Budget__c> testBudgets = new List<Budget__c>([
			SELECT
				Id,
				Invoice_Total_Amount__c
			FROM
				Budget__c
			WHERE
				Id = :modifiedInvoiceLine.Budget__c]);
		System.assertEquals(1, testBudgets.size());
		Budget__c testBudget = testBudgets.get(0);
		System.assertEquals(0, testBudget.Invoice_Total_Amount__c);
	}
	
	@isTest
	private static void test_LinkInvoicelineBudgets_AccountDelete()
	{
		Integer PRODUCT_CHUNK = 3;
		Set<Id> budgetSet = new set<Id>();
		Set<Id> invoiceLineSet = new Set<Id>();
		Invoice_Line__c modifiedInvoiceLine = null;
		List<String> productCodeList = new List<String>{ '12345', '17226', '27366' };
		List<Budget__c> budgetCache = new List<Budget__c>();
		List<Product2> productCache = new List<Product2>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
		List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
		Pricebook2 pricebook, standardPricebook;
		Integer i, j;
		
		List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
		if (!scheduleSettings.isEmpty())
		{
			for (Schedule_Settings__c scheduleSetting : scheduleSettings)
			{
				scheduleSetting.Global_Schedule_Interval__c = 'M1';
			}
			update scheduleSettings;
		}
		else
		{
			Schedule_Settings__c setting = new Schedule_Settings__c(
				Name = 'Default',
				Global_Schedule_Interval__c = 'M1');
			insert setting;
			System.assertNotEquals(setting.Id, null);
		}
		
		for (Pricebook2 pricebook2 : [
			SELECT
				Id,
				IsStandard,
				IsActive
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			OR
				IsActive = true])
		{
			if (pricebook2.isStandard)
			{
				standardPricebook = pricebook2;
			}
			if (pricebook2.isActive)
			{
				pricebook = pricebook2;
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
					break;
				}
			}
		}
		
		for (i = 0; i < PRODUCT_CHUNK; i++)
		{
			Product2 product = new Product2(
				Name = 'Product ' + i,
				IsActive = true,
				ProductCode = productCodeList.get(i));
			productCache.add(product);
		}
		insert productCache;

		Account account = new Account(
			Name = 'Apex Test Account',
			RevId__c = 'testAccount');
		insert account;
		System.assertNotEquals(account.Id, null);
		
		Date dtBudget = Date.today().addYears(10).toStartOfMonth();
		for (i = 0; i < 12; i++)
		{
			for (Product2 product : productCache)
			{
				Budget__c budget = new Budget__c(
					Budget_Date__c = dtBudget.addMonths(i),
					Account__c = account.Id,
					Product__c = product.Id);
				budgetCache.add(budget);
			}
		}
		insert budgetCache;
		for (Budget__c budget : budgetCache)
		{
			budgetSet.add(budget.Id);
		}
		
		for (Product2 product : productCache)
		{
			Invoice_Line__c invoiceLine = new Invoice_Line__c(
				RevId__c = account.RevId__c,
				Accounting_Period__c = Date.today().addYears(10),
				Amount__c = 12000,
				Salesforce_Product__c = product.productCode);
			invoiceLineCache.add(invoiceLine);
		}
		insert invoiceLineCache;
		
		for (Invoice_Line__c invoiceLine : invoiceLineCache)
		{
			invoiceLineSet.add(invoiceLine.Id);
		}
		
		budgetSet.clear();
		
		for (Invoice_Line__c testInvoiceLine : [
			SELECT
				Amount__c,
				Budget__c,
				Budget__r.Invoice_Total_Amount__c,
				RevId__c,
				Account__c,
				Accounting_Period__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet])
		{
			budgetSet.add(testInvoiceLine.Budget__c);
			System.assertEquals(true, budgetSet.contains(testInvoiceLine.Budget__c));
			System.assertEquals(testInvoiceLine.Amount__c, testInvoiceLine.Budget__r.Invoice_Total_Amount__c);
		}
		
		delete invoiceLineCache;

		for (Budget__c testBudget : [
			SELECT
				Id,
				Invoice_Total_Amount__c
			FROM
				Budget__c
			WHERE
				Id IN :budgetSet])
		{
			System.assertEquals(0, testBudget.Invoice_Total_Amount__c);
		}
	}
	
	@isTest
	private static void test_LinkInvoicelineProducts()
	{
		Integer PRODUCT_CHUNK = 3;
		List<String> productCodeList = new List<String>{ '12345', '17226', '27366' };
		List<Product2> productCache = new List<Product2>();
		List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
		List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		Map<String, Id> productCodeKeyedProductMap = new Map<String, Id>();
		Set<Id> invoiceLineSet = new Set<Id>();
		Pricebook2 pricebook, standardPricebook;
		Integer i, j;
		
		
		for (Pricebook2 pricebook2 : [
			SELECT
				Id,
				IsStandard,
				IsActive
			FROM
				Pricebook2
			WHERE
				IsStandard = true
			OR
				IsActive = true])
		{
			if (pricebook2.isStandard)
			{
				standardPricebook = pricebook2;
			}
			if (pricebook2.isActive)
			{
				pricebook = pricebook2;
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
					break;
				}
			}
		}
		
		for (i = 0; i < PRODUCT_CHUNK; i++)
		{
			Product2 product = new Product2(
				Name = 'Product ' + i,
				IsActive = true,
				ProductCode = productCodeList.get(i));
			productCache.add(product);
		}
		insert productCache;
		
		for (Product2 product : productCache)
		{
			productCodeKeyedProductMap.put(product.ProductCode, product.Id);
		}
		
		Account account = new Account(
			Name = 'Apex Test Account',
			RevId__c = 'testAccount');
		insert account;
		System.assertNotEquals(account.Id, null);
		
		for (Product2 product : productCache)
		{
			Invoice_Line__c invoiceLine = new Invoice_Line__c(
				RevId__c = account.RevId__c,
				Accounting_Period__c = Date.today().addYears(10),
				Amount__c = 12000,
				Salesforce_Product__c = product.productCode);
			invoiceLineCache.add(invoiceLine);
		}
		insert invoiceLineCache;
		
		for (Invoice_Line__c invoiceLine : invoiceLineCache)
		{
			invoiceLineSet.add(invoiceLine.Id);
		}
		
		for (Invoice_Line__c testInvoiceLine : [
			SELECT
				Id,
				Product__c,
				Salesforce_Product__c
			FROM
				Invoice_Line__c
			WHERE
				Id IN :invoiceLineSet])
		{
			System.assertEquals(productCodeKeyedProductMap.get(testInvoiceLine.Salesforce_Product__c), testInvoiceLine.Product__c);
		}
	}
}