src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Committed_Lives__c</fullName>
        <formula>Near_Site_Opportunity__r.Committed_Lives__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Total Number of Committed Lives at the associated Opportunity</inlineHelpText>
        <label>Opp Committed Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Near_Site_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Opportunity (Clinic) to which this Account is associated.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Accounts</relationshipLabel>
        <relationshipName>NearSiteAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Lives__c</fullName>
        <inlineHelpText>The total number of lives used to calculate the amount invoiced to client (e.g. PEPM, revenue calculation)</inlineHelpText>
        <label>Number of Eligible Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <inlineHelpText>The Probability associated with the Stage. This field is automatically populated based on the Stage selected.</inlineHelpText>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Weighted_Number_of_Lives__c</fullName>
        <formula>Number_of_Lives__c *  Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Number of Lives * Probability</inlineHelpText>
        <label>Weighted Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Committed_Lives__c</fullName>
        <inlineHelpText>Total number of Committed Lives from all associated Accounts.
Committed Lives = Account is 100% Committed.</inlineHelpText>
        <label>Committed Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Potential_Lives__c</fullName>
        <inlineHelpText>The potential lives at the company</inlineHelpText>
        <label>Potential Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weighted_Number_of_Lives__c</fullName>
        <inlineHelpText>The Sum of all Associated Accounts &quot;Weighted Number of Lives&quot;</inlineHelpText>
        <label>Weighted Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/XONearSiteAccountTriggerHandler.cls
public with sharing class XONearSiteAccountTriggerHandler {

	private List<ITriggerHandler> handlers;
	private List<Account> newValues;
	private List<Account> oldValues;

	public static String nearSiteOppoTypeId =
		(Schema.SObjectType.Opportunity.getRecordTypeInfosByName().containsKey('Near-Site')) ?
		(Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Near-Site').getRecordTypeId()) :
		null;

	public XONearSiteAccountTriggerHandler(
		List<ITriggerHandler> handlers,
		List<Account> newValues,
		List<Account> oldValues) {

		this.handlers = handlers;
		this.newValues = newValues;
		this.oldValues = oldValues;
	}

	public void execute() {
		for (ITriggerHandler handler : this.handlers) {
			handler.execute(this.newValues, this.oldValues);
		}
	}

	public class NearSiteLivesCalculator implements ITriggerHandler {

		public void execute(List<Account> newValues, List<Account> oldValues) {
			if (newValues == null
				|| XONearSiteAccountTriggerHandler.nearSiteOppoTypeId == null) {

				return;
			}

			Map<Id, Opportunity> opposToUpdate = new Map<Id, Opportunity>();

			List<Id> oppoIds = new List<Id>();
			for (Account acc : newValues) {
					oppoIds.add(acc.Near_Site_Opportunity__c);
			}

			List<Opportunity> committedOppos = [
				SELECT
				(
					SELECT Number_of_Lives__c
					FROM NearSiteAccounts__r
					WHERE Probability__c = 100
						AND Number_of_Lives__c != null
				)
				FROM Opportunity
				WHERE Id IN :oppoIds
					AND RecordTypeId = :XONearSiteAccountTriggerHandler.nearSiteOppoTypeId
			];
			for (Opportunity opp : committedOppos) {
				Decimal lives = 0;
				for (Account nsAcc : opp.NearSiteAccounts__r) {
					lives += nsAcc.Number_of_Lives__c;
				}

				if (!opposToUpdate.containsKey(opp.Id)) {
					opp.Committed_Lives__c = lives;
					opposToUpdate.put(opp.Id, opp);
				}
				else {
					opposToUpdate.get(opp.Id).Committed_Lives__c = lives;
				}
			}

			List<Opportunity> totalLivesOppos = [
				SELECT
				(
					SELECT Number_of_Lives__c
					FROM NearSiteAccounts__r
					WHERE Number_of_Lives__c != null
				)
				FROM Opportunity
				WHERE Id IN :oppoIds
					AND RecordTypeId = :XONearSiteAccountTriggerHandler.nearSiteOppoTypeId
			];
			for (Opportunity opp : totalLivesOppos) {
				Decimal lives = 0;
				for (Account nsAcc : opp.NearSiteAccounts__r) {
					lives += nsAcc.Number_of_Lives__c;
				}

				if (!opposToUpdate.containsKey(opp.Id)) {
					opp.Potential_Lives__c = lives;
					opposToUpdate.put(opp.Id, opp);
				}
				else {
					opposToUpdate.get(opp.Id).Potential_Lives__c = lives;
				}
			}

			List<Opportunity> weightedLivesOppos = [
				SELECT
				(
					SELECT Weighted_Number_of_Lives__c
					FROM NearSiteAccounts__r
					WHERE Weighted_Number_of_Lives__c != null
				)
				FROM Opportunity
				WHERE Id IN :oppoIds
					AND RecordTypeId = :XONearSiteAccountTriggerHandler.nearSiteOppoTypeId
			];
			for (Opportunity opp : weightedLivesOppos) {
				Decimal lives = 0;
				for (Account nsAcc : opp.NearSiteAccounts__r) {
					lives += nsAcc.Weighted_Number_of_Lives__c;
				}

				if (!opposToUpdate.containsKey(opp.Id)) {
					opp.Weighted_Number_of_Lives__c = lives;
					opposToUpdate.put(opp.Id, opp);
				}
				else {
					opposToUpdate.get(opp.Id).Weighted_Number_of_Lives__c = lives;
				}
			}

			update opposToUpdate.values();
		}

	}

}