src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Contract Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Committed_Lives__c</fullName>
        <formula>Near_Site_Opportunity__r.Committed_Lives__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Total Number of Committed Lives at the associated Opportunity</inlineHelpText>
        <label>Opp Committed Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Near_Site_Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The Opportunity (Clinic) to which this Account is associated.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Accounts</relationshipLabel>
        <relationshipName>NearSiteAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Lives__c</fullName>
        <inlineHelpText>The total number of lives used to calculate the amount invoiced to client (e.g. PEPM, revenue calculation)</inlineHelpText>
        <label>Number of Eligible Employees</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <inlineHelpText>The Probability associated with the Stage. This field is automatically populated based on the Stage selected.</inlineHelpText>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Near_Site_Opportunity__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weighted_Number_of_Lives__c</fullName>
        <formula>Number_of_Lives__c *  Probability__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Number of Lives * Probability</inlineHelpText>
        <label>Weighted Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Clinic_Launch_Date__c</fullName>
        <inlineHelpText>The day you anticipate the product going live and thereby getting revenue</inlineHelpText>
        <label>Live Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Committed_Lives__c</fullName>
        <inlineHelpText>Total number of Committed Lives from all associated Accounts.
Committed Lives = Account is 100% Committed.</inlineHelpText>
        <label>Committed Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <label>Client Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Health Plan / TPA</fullName>
                </value>
                <value>
                    <fullName>Employers</fullName>
                    <default>true</default>
                    <label>Employers</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Potential_Lives__c</fullName>
        <inlineHelpText>The potential lives at the company</inlineHelpText>
        <label>Potential Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Bay Area</fullName>
                </value>
                <value>
                    <fullName>Boston</fullName>
                </value>
                <value>
                    <fullName>Central CT</fullName>
                </value>
                <value>
                    <fullName>Central Florida</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Coastal CT</fullName>
                </value>
                <value>
                    <fullName>Conneticut</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>North Florida</fullName>
                </value>
                <value>
                    <fullName>North NJ</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>NYC</fullName>
                </value>
                <value>
                    <fullName>NY South</fullName>
                </value>
                <value>
                    <fullName>Philadelphia</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Raleigh</fullName>
                </value>
                <value>
                    <fullName>Richmond</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>Southern California</fullName>
                </value>
                <value>
                    <fullName>South Florida</fullName>
                </value>
                <value>
                    <fullName>Utah</fullName>
                </value>
                <value>
                    <fullName>Winston-Salem</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>Is this brand new business revenue?  Under contract revenue?  Or contract renewal revenue?</description>
        <label>Revenue Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                    <default>true</default>
                    <label>New SOW</label>
                </value>
                <value>
                    <fullName>Under Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
                <value>
                    <fullName>TX</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>NJ</fullName>
                </value>
                <value>
                    <fullName>PA</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>UT</fullName>
                </value>
                <value>
                    <fullName>WA</fullName>
                </value>
                <value>
                    <fullName>NC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Weighted_Number_of_Lives__c</fullName>
        <inlineHelpText>The Sum of all Associated Accounts &quot;Weighted Number of Lives&quot;</inlineHelpText>
        <label>Weighted Number of Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/XONearSiteAccountTriggerHandlerTest.cls
@isTest
private class XONearSiteAccountTriggerHandlerTest {

    private static Account acc;
    private static Opportunity oppo;

    private static void init() {
        acc = new Account(
            Name = 'Test'
        );
        insert acc;

        oppo = new Opportunity(
            RecordTypeId = XONearSiteAccountTriggerHandler.nearSiteOppoTypeId,
            Name = 'Test',
            AccountId = acc.Id,
            Type = 'Transition',
            Opportunity_Type__c = 'Near-Site',
            State__c = 'NY',
            Region__c = 'NYC',
            StageName = 'Closed Won',
            Clinic_Launch_Date__c = Date.today(),
            CloseDate = Date.today(),
			Revenue_Type__c = '	New Business'
        );System.debug('OPP: ' + oppo);
        insert oppo;
    }

    @isTest static void testCommitedLivesCalc_Success() {
        if (XONearSiteAccountTriggerHandler.nearSiteOppoTypeId == null) {
            return;
        }
        init();

        Test.startTest();

        insert new Account(
            Name = 'Test 1',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        insert new Account(
            Name = 'Test 2',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 10
        );

        insert new Account(
            Name = 'Test 3',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 99,
            Number_of_Lives__c = 15
        );

        Test.stopTest();

        System.assertEquals(15, Integer.valueOf([SELECT Committed_Lives__c FROM Opportunity LIMIT 1].Committed_Lives__c));
    }

 /*   @isTest static void testPotentialLivesCalc_Success() {
        if (XONearSiteAccountTriggerHandler.nearSiteOppoTypeId == null) {
            return;
        }
        init();

        Test.startTest();

        insert new Account(
            Name = 'Test 1',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        insert new Account(
            Name = 'Test 2',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 10
        );

        insert new Account(
            Name = 'Test 3',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 99,
            Number_of_Lives__c = 15
        );

        Test.stopTest();

        System.assertEquals(30, Integer.valueOf([SELECT Potential_Lives__c FROM Opportunity LIMIT 1].Potential_Lives__c));
    }

    @isTest static void testWeightedLivesCalc_Success() {
        if (XONearSiteAccountTriggerHandler.nearSiteOppoTypeId == null) {

            return;
        }
        init();

        Test.startTest();

        insert new Account(
            Name = 'Test 1',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        insert new Account(
            Name = 'Test 2',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 10
        );

        insert new Account(
            Name = 'Test 3',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 50,
            Number_of_Lives__c = 10
        );

        Test.stopTest();

        System.assertEquals(20, Integer.valueOf([SELECT Weighted_Number_of_Lives__c FROM Opportunity LIMIT 1].Weighted_Number_of_Lives__c));
    }
    
        @isTest static void testWeightedLivesCalc_Success2() {
        if (XONearSiteAccountTriggerHandler.nearSiteOppoTypeId == null) {

            return;
        }
        init();

        Test.startTest();

        insert new Account(
            Name = 'Test 1',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        insert new Account(
            Name = 'Test 2',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 10
        );

        insert new Account(
            Name = 'Test 3',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 50,
            Number_of_Lives__c = 10
        );

        Test.stopTest();

        System.assertEquals(20, Integer.valueOf([SELECT Weighted_Number_of_Lives__c FROM Opportunity LIMIT 1].Weighted_Number_of_Lives__c));
    }

    @isTest static void testCommitedLivesCalc_OnDeleteSuccess() {
        if (XONearSiteAccountTriggerHandler.nearSiteOppoTypeId == null) {

            return;
        }
        init();

        Test.startTest();

        insert new Account(
            Name = 'Test 1',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        insert new Account(
            Name = 'Test 2',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        insert new Account(
            Name = 'Test 3',
            Close_Date__c = Date.today(),
            Near_Site_Opportunity__c = oppo.Id,
            Probability__c = 100,
            Number_of_Lives__c = 5
        );

        System.assertEquals(4, [SELECT Id FROM Account].size(), 'Accounts created: ' + [SELECT Id FROM Account].size());
        System.assert(![SELECT Id FROM Account WHERE Probability__c = 100 LIMIT 1].isEmpty(), 'No 100% Accounts created!: ' + [SELECT Probability__c FROM Account]);

        delete [
            SELECT Id
            FROM Account
                WHERE Probability__c = 100
            LIMIT 1
        ];

        Test.stopTest();

        System.assertEquals(10, Integer.valueOf([SELECT Committed_Lives__c FROM Opportunity LIMIT 1].Committed_Lives__c));
    }*/

}