src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <description>New Formula Field to display Account Owner - Not &quot;changeable/editable&quot;</description>
        <formula>Owner.LastName &amp; &quot;, &quot; &amp;  Owner.FirstName</formula>
        <label>Account Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RevID__c</fullName>
        <externalId>true</externalId>
        <label>RevID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <description>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</description>
        <inlineHelpText>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</inlineHelpText>
        <label>Budget Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accounting_Period__c</fullName>
        <label>Accounting Period</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RevId__c</fullName>
        <label>Rev Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Schedule</label>
        <referenceTo>Revenue_Schedule__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Line Item Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Schedule_Date__c</fullName>
        <label>Revenue Schedule Date</label>
        <type>Date</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GSP_SC_trgAccountMethods.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, 21 Jul 2020
 */
public with sharing class GSP_SC_trgAccountMethods
{
	@future
	public static void UpdateScheduleAccountOwners(Set<Id> accountSet, Map<Id, Id> oldOwnerMap)
	{
		Map<Id, List<Revenue_Schedule__c>> opportunityLineItemRevenueScheduleMap = new Map<Id, List<Revenue_Schedule__c>>();
		Map<Id, Invoice_Line__c> invoiceLineCacheMap = new Map<Id, Invoice_Line__c>();
		List<Revenue_Schedule__c> revenueScheduleCache = new List<Revenue_Schedule__c>();
		List<Budget__c> budgetCache = new List<Budget__c>();
		// Old Owner -> New Owner
		Map<Id, Id> oldOwnerKeyedOwnerMap = new Map<Id, Id>();
		Set<String> revIdSet = new Set<String>();
		
		for (Budget__c budget : [
			SELECT
				Id,
				Account__c,
				Account__r.OwnerId,
				OwnerId
			FROM
				Budget__c
			WHERE
				Account__c IN :accountSet])
		{
			budget.Ownerid = budget.Account__r.OwnerId;
			budgetCache.add(budget);
		}
		if (!budgetCache.isEmpty())
		{
			update budgetCache;
		}
		
		for (Opportunity opportunity : [
			SELECT
				Id,
				AccountId,
				Account.OwnerId,
				Account.RevId__c, (
				SELECT
					Id
				FROM
					OpportunityLineItems), (
				SELECT
					Id,
					Account__c,
					Account_Owner__c,
					Budget__c,
					Product__c,
					Opportunity_Line_Item_Id__c,
					Revenue_Schedule_Date__c
				FROM
					Revenue_Schedules__r
				ORDER BY
					Opportunity_Line_Item_Id__c, Revenue_Schedule_Date__c)
			FROM
				Opportunity
			WHERE
				AccountId IN :accountSet])
		{
			revIdSet.add(opportunity.Account.RevId__c);
			if (oldOwnerMap.containsKey(opportunity.AccountId) &&
				!oldOwnerKeyedOwnerMap.containsKey(opportunity.Account.OwnerId))
			{
				oldOwnerKeyedOwnerMap.put(oldOwnerMap.get(opportunity.AccountId), opportunity.Account.OwnerId);
			}
			for (OpportunityLineItem opportunityLineItem : opportunity.OpportunityLineItems)
			{
				if (!opportunityLineItemRevenueScheduleMap.containsKey(opportunityLineItem.Id))
				{
					opportunityLineItemRevenueScheduleMap.put(opportunityLineItem.Id, new List<Revenue_Schedule__c>());
				}
			}
			for (Revenue_Schedule__c revenueSchedule : opportunity.Revenue_Schedules__r)
			{ 
				if (revenueSchedule.Account_Owner__c != opportunity.Account.OwnerId)
				{
					revenueSchedule.Account_Owner__c = opportunity.Account.OwnerId;
					revenueScheduleCache.add(revenueSchedule);
				}
				System.assertEquals(true, opportunityLineItemRevenueScheduleMap.containsKey((Id)revenueSchedule.Opportunity_Line_Item_Id__c));
				opportunityLineItemRevenueScheduleMap.get((Id)revenueSchedule.Opportunity_Line_Item_Id__c).add(revenueSchedule);
			}
		}
		if (!revenueScheduleCache.isEmpty())
		{
			GSP_SC_ScheduleHelper.LinkBudgets(revenueScheduleCache, opportunityLineItemRevenueScheduleMap, true);
		}
		
		Set<Integer> monthSet = new Set<Integer>(),
			yearSet = new Set<Integer>();
		Map<Id, Map<Integer, Map<Integer, Budget__c>>> budgetSearchMap = new Map<Id, Map<Integer, Map<Integer, Budget__c>>>();
		Set<Id> budgetSet = new Set<Id>();
		
		List<Invoice_Line__c> invoiceLineList = new List<Invoice_Line__c>([
			SELECT
				Id,
				RevId__c,
				Accounting_Period__c,
				Budget__c,
				Budget__r.Account_Owner__c
			FROM
				Invoice_Line__c
			WHERE
				Budget__r.Account_Owner__c IN : oldOwnerKeyedOwnerMap.keySet()
			AND
				RevId__c IN :revIdSet]);
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			monthSet.add(invoiceLine.Accounting_Period__c.month());
			yearSet.add(invoiceLine.Accounting_Period__c.year());
		}
		
		for (Budget__c budget : [
			SELECT
				Id,
				Budget_Date__c,
				Account_Owner__c
			FROM
				Budget__c
			WHERE
				CALENDAR_YEAR(Budget_Date__c) IN :yearSet
			AND
				CALENDAR_MONTH(Budget_Date__c) IN :monthSet
			AND
				Account_Owner__c IN :oldOwnerKeyedOwnerMap.values()])
		{
			if (!budgetSearchMap.containsKey(budget.Account_Owner__c))
			{
				budgetSearchMap.put(budget.Account_Owner__c, new Map<Integer, Map<Integer, Budget__c>>());
			}
			if (!budgetSearchMap.get(budget.Account_Owner__c).containsKey(budget.Budget_Date__c.year()))
			{
				budgetSearchMap.get(budget.Account_Owner__c).put(budget.Budget_Date__c.year(), new Map<Integer, Budget__c>());
			}
			budgetSearchMap.get(budget.Account_Owner__c).get(budget.Budget_Date__c.year()).put(budget.Budget_Date__c.month(), budget);
		}
		
		for (Invoice_Line__c invoiceLine : invoiceLineList)
		{
			if (invoiceLine.Budget__c != null)
			{
				budgetSet.add(invoiceLine.Budget__c);
				invoiceLine.Budget__c = null;
				invoiceLineCacheMap.put(invoiceLine.Id, invoiceLine);
			}
			if (oldOwnerKeyedOwnerMap.containsKey(invoiceLine.Budget__r.Account_Owner__c))
			{
				Id id = oldOwnerKeyedOwnerMap.get(invoiceLine.Budget__r.Account_Owner__c);
				if (budgetSearchMap.containsKey(id))
				{
					if (budgetSearchMap.get(id).containsKey(invoiceLine.Accounting_Period__c.year()))
					{
						if (budgetSearchMap.get(id).get(invoiceLine.Accounting_Period__c.year()).containsKey(invoiceLine.Accounting_Period__c.month()))
						{
							Id budgetId = budgetSearchMap.get(id).get(invoiceLine.Accounting_Period__c.year()).
								get(invoiceLine.Accounting_Period__c.month()).Id;
							invoiceLine.Budget__c = budgetId;
							budgetSet.add(budgetId);
							invoiceLineCacheMap.put(invoiceLine.Id, invoiceLine);
						}
					}
				}
			}
		}
		
		if (!invoiceLineCacheMap.isEmpty())
		{
			update invoiceLineCacheMap.values();
		}
		if (!budgetSet.isEmpty())
		{
			GSP_SC_BudgetHelper.RollUpInvoiceValues(budgetSet);
		}
	}
}