src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <description>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</description>
        <inlineHelpText>Only the Month / Year portion of this date is used for calculations, the Day is ignored.</inlineHelpText>
        <label>Budget Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <description>Is this brand new business revenue?  Under contract revenue?  Or contract renewal revenue?</description>
        <label>Revenue Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                    <default>true</default>
                    <label>New SOW</label>
                </value>
                <value>
                    <fullName>Under Contract</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Pricing_Model__c</fullName>
        <label>Pricing Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Forecast Model</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
                <value>
                    <fullName>Private Care Team</fullName>
                </value>
                <value>
                    <fullName>Shared Care Team</fullName>
                </value>
                <value>
                    <fullName>Cost+</fullName>
                    <isActive>false</isActive>
                    <label>Cost+</label>
                </value>
                <value>
                    <fullName>Fixed Fee</fullName>
                    <isActive>false</isActive>
                    <label>Fixed Fee</label>
                </value>
                <value>
                    <fullName>PEPM</fullName>
                    <isActive>false</isActive>
                    <label>PEPM</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Type__c</fullName>
        <label>Revenue Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IMPORTANT: One Setting with the Name set to &apos;Default&apos;</description>
    <fields>
        <fullName>Global_Schedule_Interval__c</fullName>
        <description>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1</description>
        <inlineHelpText>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1</inlineHelpText>
        <label>Global Schedule Interval</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Schedule Settings</label>
</CustomObject>

src/classes/GSP_SC_ScheduleHelper_TEST.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, June, 2020
 */
@isTest
private class GSP_SC_ScheduleHelper_TEST
{
	@isTest(seeAlldata=true)
	private static void test_BatchUpdateSalesforceSchedules()
	{
		if (Schema.getGlobalDescribe().containsKey('OpportunityLineItemSchedule'))
		{
			Integer PRODUCT_CHUNK = 3;
			Integer REVENUE_MONTHS = 12;
			Integer LINE_ITEM_CHUNK = 4;
			Integer SCHEDULE_CHUNK = 3;
			Set<Id> opportunityLineItemSet = new Set<Id>();
			Set<Id> budgetSet = new set<Id>();
			List<Product2> productCache = new List<Product2>();
			List<PricebookEntry> pricebookEntryCache = new List<PricebookEntry>();
			List<PricebookEntry> standardPricebookEntryCache = new List<PricebookEntry>();
			List<OpportunityLineItem> opportunityLineItemCache = new List<OpportunityLineItem>();
			List<Budget__c> budgetCache = new List<Budget__c>();
			List<sObject> opportunityLineItemScheduleCache = new List<sObject>();
			Map<Id, OpportunityLineItem> opportunityLineItemMap = new Map<Id, OpportunityLineItem>();
			Map<String, List<Revenue_Schedule__c>> testRevenueScheduleMap = new Map<String, List<Revenue_Schedule__c>>(); 
			Pricebook2 pricebook, standardPricebook;
			Integer i, j;
			
			List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
			if (!scheduleSettings.isEmpty())
			{
				for (Schedule_Settings__c scheduleSetting : scheduleSettings)
				{
					scheduleSetting.Global_Schedule_Interval__c = 'M1';
				}
				update scheduleSettings;
			}
			else
			{
				Schedule_Settings__c setting = new Schedule_Settings__c(
					Name = 'Default',
					Global_Schedule_Interval__c = 'M1');
				insert setting;
				System.assertNotEquals(setting.Id, null);
			}
			
			for (Pricebook2 pricebook2 : [
				SELECT
					Id,
					IsStandard,
					IsActive
				FROM
					Pricebook2
				WHERE
					IsStandard = true
				OR
					IsActive = true])
			{
				if (pricebook2.isStandard)
				{
					standardPricebook = pricebook2;
				}
				if (pricebook2.isActive)
				{
					pricebook = pricebook2;
					if (pricebook2.isStandard)
					{
						standardPricebook = pricebook2;
						break;
					}
				}
			}
			
			for (i = 0; i < PRODUCT_CHUNK; i++)
			{
				Product2 product = new Product2(
					Name = 'Product ' + i,
					IsActive = true);
					try
					{
						product.put('CanUseRevenueSchedule', true);
					}
					catch (Exception ex){}
					try
					{
						product.put('CanUseQuantitySchedule', true);
					}
					catch (Exception ex){}
				productCache.add(product);
			}
			insert productCache;
			
			for (i = 0; i < PRODUCT_CHUNK; i++)
			{
				if (pricebook != standardPricebook)
				{
					PricebookEntry pricebookEntry = new PricebookEntry(
						Pricebook2Id = standardPricebook.Id,
						Product2Id = productCache.get(i).Id,
						UnitPrice = (i + 1) * 7,
						IsActive = standardPricebook.isActive);
					standardPricebookEntryCache.add(pricebookEntry);
				}
				PricebookEntry pricebookEntry = new PricebookEntry(
					Pricebook2Id = pricebook.Id,
					Product2Id = productCache.get(i).Id,
					UnitPrice = (i + 1) * 7,
					IsActive = true);
				pricebookEntrycache.add(pricebookEntry);
			}
			
			if (!standardPricebookEntryCache.isEmpty())
			{
				insert standardPricebookEntryCache;
			}
			insert pricebookEntryCache;

			Account account = new Account(
				Name = 'Apex Test Account');
			insert account;
			System.assertNotEquals(account.Id, null);
			
			Date dtBudget = Date.today().addYears(10).toStartOfMonth();
			for (i = 0; i < 12; i++)
			{
				for (Product2 product : productCache)
				{
					Budget__c budget = new Budget__c(
						Budget_Date__c = dtBudget.addMonths(i),
						Account__c = account.Id,
						Product__c = product.Id);
					budgetCache.add(budget);
				}
			}
			insert budgetCache;
			for (Budget__c budget : budgetCache)
			{
				budgetSet.add(budget.Id);
			}
			
			Opportunity opportunity = new Opportunity(
				Name = 'Apex Test Opportunity',
				StageName = 'Prospecting',
				CloseDate = Date.today().addYears(10),
				AccountId = account.Id,
				Revenue_Type__c = '	New Business');
			insert opportunity;
			System.assertNotEquals(opportunity.Id, null);
			
			for (i = 0; i < LINE_ITEM_CHUNK; i++)
			{
				OpportunityLineItem opportunityLineItem = new OpportunityLineItem(
					OpportunityId = opportunity.Id,
					PricebookEntryId = pricebookEntryCache.get(i == 3 ? i - 1 : i).Id,
					UnitPrice = 12000,
					Quantity = 1,
					Pricing_Model__c = 'PEPM');
				opportunityLineItemCache.add(opportunityLineItem);
			}
			
			GSP_SC_TriggerContext.DisableOpportunityLineItemTriggers = true;		// Prevent schedule creation
			insert opportunityLineItemCache;
			
			for (opportunityLineItem opportunityLineItem : opportunityLineItemCache)
			{
				opportunityLineItemSet.add(opportunityLineItem.Id);
				Date dt = Date.today().addYears(10);
				for (i = 0; i < SCHEDULE_CHUNK; i++)
				{
					sObject schedule = Schema.getGlobalDescribe().get('OpportunityLineItemSchedule').newSObject();
					schedule.put('Type', 'Revenue');
					schedule.put('ScheduleDate', dt);
					schedule.put('Revenue', 1000 * i);
					schedule.put('OpportunityLineItemId', opportunityLineItem.Id);
					opportunityLineItemScheduleCache.add(schedule);
					dt = dt.addMonths(1);
				}
			}
			insert opportunityLineItemScheduleCache;
			
			String strSOQL = 'SELECT Id, HasSchedule, TotalPrice, (SELECT Type, Revenue, ScheduleDate FROM OpportunityLineItemSchedules' +
				' ORDER BY ScheduleDate) FROM OpportunityLineItem WHERE Id IN :opportunityLineItemSet';
			
			List<OpportunityLineItem> testOpportunityLineItems = Database.query(strSOQL);
			System.assertEquals(LINE_ITEM_CHUNK, testOpportunityLineItems.size());
			for (OpportunityLineItem testOpportunityLineItem : testOpportunityLineItems)
			{
				System.assertEquals(SCHEDULE_CHUNK, testOpportunityLineItem.getSObjects('OpportunityLineItemSchedules').size());
			}
			
			GSP_SC_ScheduleHelper.BatchUpdateSalesforceSchedules(opportunityLineItemCache, 'Straight Line');
			
			testOpportunityLineItems = Database.query(strSOQL);
			System.assertEquals(LINE_ITEM_CHUNK, testOpportunityLineItems.size());
			for (OpportunityLineItem testOpportunityLineItem : testOpportunityLineItems)
			{
				System.assertEquals(null, testOpportunityLineItem.getSObjects('OpportunityLineItemSchedules'));	// All salesforce schedules deleted
			}
		}
	}
}