src/objects/Budget__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Budgets</relationshipLabel>
        <relationshipName>Budgets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Budget</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic__c.object
<CustomObject>
    <description>This object will store available Clinics available for selection on Patient Referrals.</description>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <label>Clinic</label>
    <nameField>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <referenceTo>Clinic__c</referenceTo>
        <relationshipLabel>Clinic Budgets</relationshipLabel>
        <relationshipName>Clinic_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clinic Budget</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinic Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinic Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Clinic__c</fullName>
        <inlineHelpText>This represents what clinic this population be primarily accessing or what clinic was the client sold.</inlineHelpText>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Start_Date__c</fullName>
        <inlineHelpText>Represents the calculation of when this revenue line starts.</inlineHelpText>
        <label>Revenue Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Schedule_Interval_Override__c</fullName>
        <description>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1
This overrides the Global Shedule Interval defined in the &apos;Schedule Settings&apos; Custom Setting</description>
        <inlineHelpText>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1
This overrides the Global Shedule Interval defined in the &apos;Schedule Settings&apos; Custom Setting</inlineHelpText>
        <label>Schedule Interval Override</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget</label>
        <referenceTo>Budget__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Line_Item_Id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Line Item Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Schedule_Date__c</fullName>
        <label>Revenue Schedule Date</label>
        <type>Date</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Schedule_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IMPORTANT: One Setting with the Name set to &apos;Default&apos;</description>
    <fields>
        <fullName>Global_Schedule_Interval__c</fullName>
        <description>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1</description>
        <inlineHelpText>Format for this field is one of &apos;Dxxx&apos;, &apos;Mxxx&apos;, &apos;Yxxx&apos; where &apos;xxx&apos; is the number of Days, Months or Years. e.g. M1, D7, Y1</inlineHelpText>
        <label>Global Schedule Interval</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Schedule Settings</label>
</CustomObject>

src/classes/GSP_SC_trgOpportunityLineItemMethods.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, June, 2020
 */
public with sharing class GSP_SC_trgOpportunityLineItemMethods
{
	public static void UpdateScheduleSize(Set<Id> opportunityLineItemSet)
	{
		GSP_SC_ScheduleHelper.ModifyScheduleStructure(opportunityLineItemSet, true);
	}
	
	public static void UpdateRevenueDates(Map<Id, OpportunityLineItem>  opportunityLineItemMap)
	{
		if ((Schema.sObjectType.Revenue_Schedule__c.isAccessible() &&
			Schema.sObjectType.Revenue_Schedule__c.isCreateable() &&
			Schema.sObjectType.Revenue_Schedule__c.isUpdateable() &&
			Schema.sObjectType.Revenue_Schedule__c.isDeletable()) ||
			test.isRunningTest())
		{
			Map<Id, List<Revenue_Schedule__c>> opportunityLineItemKeyedRevenueScheduleMap = new Map<Id, List<Revenue_Schedule__c>>();
			Set<Id> opportunitySet = new Set<Id>();
			Map<Id, OpportunityLineItem> opportunityLineItemSearchMap = new Map<Id, OpportunityLineItem>();
			List<Revenue_Schedule__c> revenueScheduleCache = new List<Revenue_Schedule__c>();
			List<Schedule_Settings__c> scheduleSettings = Schedule_Settings__c.getAll().values();
			Integer nGlobalOffset = 1;
			String strGlobalInterval = 'M';

			if (!scheduleSettings.isEmpty() && !String.isEmpty(scheduleSettings.get(0).Global_Schedule_Interval__c))
			{
				try
				{
					String strInterval = scheduleSettings.get(0).Global_Schedule_Interval__c.left(1);
					Integer nOffset = Integer.valueOf(scheduleSettings.get(0).Global_Schedule_Interval__c.mid(1, 10));
					if (strInterval == 'Y' ||
						strInterval == 'M' ||
						strInterval == 'D')
					{
						strGlobalInterval = strInterval;
						nGlobalOffset = nOffset;
					}
				}
				catch (Exception ex){}
			}
			
			for (OpportunityLineItem opportunityLineItem : opportunityLineItemMap.values())
			{
				opportunitySet.add(opportunityLineItem.OpportunityId);
			}
			
			for (Opportunity opportunity : [
				SELECT
					Id, (
					SELECT
						Id,
						Revenue_Start_Date__c,
						PricebookEntry.Product2.Schedule_Interval_Override__c
					FROM
						OpportunityLineItems
					WHERE
						Id IN :opportunityLineItemMap.keySet()), (
					SELECT
						Id,
						Account__c,
						Account_Owner__c,
						Budget__c,
						Product__c,
						Revenue_Schedule_Date__c,
						Opportunity_Line_Item_Id__c
					FROM
						Revenue_Schedules__r
					WHERE
						Opportunity_Line_Item_Id__c IN :opportunityLineItemMap.keySet()
					ORDER BY
						Opportunity_Line_Item_Id__c, Revenue_Schedule_Date__c)
				FROM
					Opportunity
				WHERE
					Id IN :opportunitySet])
			{
				for (OpportunityLineItem opportunityLineItem : opportunity.OpportunityLineItems)
				{
					opportunityLineItemSearchMap.put(opportunityLineItem.Id, opportunityLineItem);
					System.assertEquals(true, opportunityLineItemMap.containsKey(opportunityLineItem.Id));
					opportunityLineItemKeyedRevenueScheduleMap.put(opportunityLineItem.Id, new List<Revenue_Schedule__c>());
				}
				
				for (Revenue_Schedule__c revenueSchedule : opportunity.Revenue_Schedules__r)
				{
					System.assertEquals(true, opportunityLineItemKeyedRevenueScheduleMap.containsKey(revenueSchedule.Opportunity_Line_Item_Id__c));
					opportunityLineItemKeyedRevenueScheduleMap.get(revenueSchedule.Opportunity_Line_Item_Id__c).add(revenueSchedule);
				}
			}
	
			for (Id id : opportunityLineItemKeyedRevenueScheduleMap.keySet())
			{
				if (opportunityLineItemMap.containsKey(id))
				{
					OpportunityLineItem opportunityLineItem = opportunityLineItemSearchMap.get(id);
					Integer nLocalOffset = nGlobalOffset;
					String strLocalInterval = strGlobalInterval;
					if (opportunityLineItem.PricebookEntry.Product2.Schedule_Interval_Override__c != null)
					{
						try
						{
							String strInterval = opportunityLineItem.PricebookEntry.Product2.Schedule_Interval_Override__c.left(1);
							Integer nOffset = Integer.valueOf(opportunityLineItem.PricebookEntry.Product2.Schedule_Interval_Override__c.mid(1, 10));
							if (strInterval == 'Y' ||
								strInterval == 'M' ||
								strInterval == 'D')
							{
								strLocalInterval = strInterval;
								nLocalOffset = nOffset;
							}
						}
						catch (Exception ex){}
					}

					OpportunityLineItem oldOpportunityLineItem = (OpportunityLineitem)trigger.oldMap.get(opportunityLineItem.Id);
					Integer days = oldOpportunityLineItem.Revenue_Start_Date__c.daysBetween(opportunityLineItem.Revenue_Start_Date__c);
					if (opportunityLineItemKeyedRevenueScheduleMap.containsKey(id) &&
						!opportunityLineItemKeyedRevenueScheduleMap.get(id).isEmpty())
					{
						Date dtSchedule,
							baseSchedule;
						for (Integer i = 0; i < opportunityLineItemKeyedRevenueScheduleMap.get(id).size(); i++)
						{
							if (Schema.sObjectType.Revenue_Schedule__c.fields.Revenue_Schedule_Date__c.isUpdateable())
							{
								Revenue_Schedule__c revenueSchedule = opportunityLineItemKeyedRevenueScheduleMap.get(id).get(i);
								if (i == 0)
								{
									revenueSchedule.Revenue_Schedule_Date__c += days;
									baseSchedule = revenueSchedule.Revenue_Schedule_Date__c;
								}
								else
								{
									revenueSchedule.Revenue_Schedule_Date__c = dtSchedule;
								}
								
								if (strLocalInterval == 'D')
								{
									dtSchedule = baseSchedule.addDays(nLocalOffset * i + 1);
								}
								else if (strLocalInterval == 'M')
								{
									dtSchedule = baseSchedule.addMonths(nLocalOffset * i + 1);
								}
								else if (strLocalInterval == 'Y')
								{
									dtSchedule = baseSchedule.addYears(nLocalOffset * i + 1);
								}
								revenueScheduleCache.add(revenueSchedule);
							}
						}
					}
				}
			}
			if (!revenueScheduleCache.isEmpty())
			{
				if (Schema.sObjectType.Revenue_Schedule__c.isUpdateable() ||
					test.isRunningTest())
				{
					update revenueScheduleCache;
				}
			}
			GSP_SC_Schedulehelper.LinkBudgets(revenueScheduleCache, opportunityLineItemKeyedRevenueScheduleMap, true);
		}
	}
	
	private static Set<Id> DeleteRevenueSchedules(List<OpportunityLineItem> opportunityLineItemList)
	{
		Set<Id> opportunitySet = new Set<Id>();
		Set<Id> budgetSet = new Set<Id>();
		Set<Id> opportunityLineItemSet = new Set<Id>();			
		List<Revenue_Schedule__c> revenueScheduleList = new List<Revenue_Schedule__c>();
		for (OpportunityLineItem opportunityLineItem : opportunityLineItemList)
		{
			opportunityLineItemSet.add(opportunityLineItem.Id);
			opportunitySet.add(opportunityLineItem.OpportunityId);
		}
			
		if (Schema.sObjectType.Revenue_Schedule__c.isAccessible())
		{
			for (Opportunity opportunity : [
				SELECT
					Id, (
					SELECT
						Budget__c
					FROM
						Revenue_Schedules__r)
				FROM
					Opportunity
				WHERE
					Id IN :opportunitySet])
			{
				for (Revenue_Schedule__c revenueSchedule : opportunity.Revenue_Schedules__r)
				{
					budgetSet.add(revenueSchedule.Budget__c);
				}
			}
			
			for (Revenue_Schedule__c revenueSchedule :[
				SELECT
					Id,
					Budget__c
				FROM
					Revenue_Schedule__c
				WHERE
					Opportunity_Line_Item_Id__c IN :opportunityLineItemSet])
			{
				revenueScheduleList.add(revenueSchedule);
			}
			
			try
			{
				if (Schema.sObjectType.Revenue_Schedule__c.isDeletable() ||
					test.isRunningTest())
				{
					delete revenueScheduleList;
					// Recalculate old budgets
					if (!budgetSet.isEmpty())
					{
						GSP_SC_BudgetHelper.RollUpScheduleValues(budgetSet);
					}
				}
			}
			catch (Exception ex){}
		}
		return opportunityLineItemSet;
	}
	
	public static void UpdateScheduleClinics(Map<Id, OpportunityLineItem> opportunityLineItemMap)
	{
		List<Revenue_Schedule__c> revenueScheduleCache = new List<Revenue_Schedule__c>();
		Map<Id, List<Revenue_Schedule__c>> revenueScheduleMap = new Map<Id, List<Revenue_Schedule__c>>(); 
		for (Id opportunityLineItemId : opportunityLineItemMap.keySet())
		{
			revenueScheduleMap.put(opportunityLineItemId, new List<Revenue_Schedule__c>());
		}
		
		for (Revenue_Schedule__c revenueSchedule : [
			SELECT
				Id,
				Revenue_Schedule_Date__c,
				Account__c,
				Account_Owner__c,
				Clinic__c,
				Clinic_Budget__c,
				Budget__c,
				Opportunity_Line_Item_Id__c
			FROM
				Revenue_Schedule__c
			WHERE
				Opportunity_Line_Item_Id__c IN :opportunityLineItemMap.keySet()])
		{
			System.assertEquals(true, revenueScheduleMap.containsKey(revenueSchedule.Opportunity_Line_Item_Id__c));
			revenueSchedule.Clinic__c = opportunityLineItemMap.get(revenueSchedule.Opportunity_Line_Item_Id__c).Clinic__c;
			revenueScheduleMap.get(revenueSchedule.Opportunity_Line_Item_Id__c).add(revenueSchedule);
			revenueScheduleCache.add(revenueSchedule);
		}
		
		GSP_SC_ScheduleHelper.LinkBudgets(revenueScheduleCache, revenueScheduleMap, true);
	}
	
	public static void DeleteSchedules(List<OpportunityLineItem> opportunityLineItemList)
	{
		DeleteRevenueSchedules(opportunityLineItemList);
	}
}