src/objects/Castlight_Account__mdt.object
<CustomObject>
    <fields>
        <fullName>Castlight_Plan__c</fullName>
        <label>Castlight Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GUID__c</fullName>
        <label>GUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Castlight Account</label>
    <pluralLabel>Castlight Accounts</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Use this record type for patients.</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Used to capture XO Patients</description>
    <fields>
        <fullName>DOB__c</fullName>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Patient Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Referral__c.object
<CustomObject>
    <description>This object will store the Patient Referrals beign managed.</description>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Patient Contact associated with the Patient Referral. Requested by Sarah L for Patient Referral Management project.</description>
        <inlineHelpText>Select the Patient Contact associated with this Patient Referral.</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Patient Referrals</relationshipLabel>
        <relationshipName>Patient_Referrals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Patient Referral</label>
    <nameField>
        <displayFormat>XOPR-{0000}</displayFormat>
        <label>Patient Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Castlight_Birthdate__c</fullName>
        <label>Castlight Birthdate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Castlight_Client_Id__c</fullName>
        <label>Castlight Client Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Castlight_First_Name__c</fullName>
        <label>Castlight First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Castlight_Last_Name__c</fullName>
        <label>Castlight Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Castlight_Lumeris_Id__c</fullName>
        <label>Castlight Lumeris Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SearchProviderController.cls
public with sharing class SearchProviderController {

    @AuraEnabled
    public static PatientObject getPatient(String recordId) {
        String objectName = String.valueOf(Id.valueOf(recordId).getSobjectType());
        PatientObject patient = new PatientObject();

        if (objectName == 'Patient_Referral__c') {
            recordId = [
                    SELECT Patient__c
                    FROM Patient_Referral__c
                    WHERE Id = :recordId
                    LIMIT 1
            ].Patient__c;

            if (String.isBlank(recordId)) {
                patient.error = 'Empty Patient in Patient Referral record.';
            } else {
                objectName = 'Contact';
            }
        }

        if (objectName == 'Contact') {
            Contact con = [
                    SELECT Id, Insurance__c
                    FROM Contact
                    WHERE Id = :recordId
                    LIMIT 1
            ];

            List<Castlight_Account__mdt> castlightIntegrations = getinsurancePlan(con.Insurance__c);

            if (castlightIntegrations.isEmpty()) {
                patient.error = 'The patient\'s plan was not found in the Castlight Reference. Provide this to your Salesforce Admin.';
            } else {
                patient.clientId = castlightIntegrations.get(0).Client_ID__c;
                patient.lumerisId = castlightIntegrations.get(0).GUID__c;
                patient.firstName = castlightIntegrations.get(0).First_Name__c;
                patient.lastName = castlightIntegrations.get(0).Last_Name__c;
                patient.insurance = con.Insurance__c;

                if (castlightIntegrations.get(0).DOB__c != null) {
                    patient.birthdate = String.valueOf(castlightIntegrations.get(0).DOB__c.year());
                    patient.birthdate += (String.valueOf(castlightIntegrations.get(0).DOB__c.month()).length() == 2) ? String.valueOf(castlightIntegrations.get(0).DOB__c.month()) : '0' + String.valueOf(castlightIntegrations.get(0).DOB__c.month());
                    patient.birthdate += (String.valueOf(castlightIntegrations.get(0).DOB__c.day()).length() == 2) ? String.valueOf(castlightIntegrations.get(0).DOB__c.day()) : '0' + String.valueOf(castlightIntegrations.get(0).DOB__c.day());
                }
            }
        } else if (objectName == 'Patient__c') {
            Patient__c pat = [
                    SELECT Id, Insurance__c
                    FROM Patient__c
                    WHERE Id = :recordId
                    LIMIT 1
            ];

            List<Castlight_Account__mdt> castlightIntegrations = getinsurancePlan(pat.Insurance__c);

            if (castlightIntegrations.isEmpty()) {
                patient.error = 'The patient\'s plan was not found in the Castlight Reference. Provide this to your Salesforce Admin.';
            } else {
                patient.clientId = castlightIntegrations.get(0).Client_ID__c;
                patient.lumerisId = castlightIntegrations.get(0).GUID__c;
                patient.firstName = castlightIntegrations.get(0).First_Name__c;
                patient.lastName = castlightIntegrations.get(0).Last_Name__c;
                patient.insurance = castlightIntegrations.get(0).Castlight_Plan__c;

                if (castlightIntegrations.get(0).DOB__c != null) {
                    patient.birthdate = String.valueOf(castlightIntegrations.get(0).DOB__c.year());
                    patient.birthdate += (String.valueOf(castlightIntegrations.get(0).DOB__c.month()).length() == 2) ? String.valueOf(castlightIntegrations.get(0).DOB__c.month()) : '0' + String.valueOf(castlightIntegrations.get(0).DOB__c.month());
                    patient.birthdate += (String.valueOf(castlightIntegrations.get(0).DOB__c.day()).length() == 2) ? String.valueOf(castlightIntegrations.get(0).DOB__c.day()) : '0' + String.valueOf(castlightIntegrations.get(0).DOB__c.day());
                }
            }
        }

        return patient;
    }

    private static List<Castlight_Account__mdt> getinsurancePlan(String insurance) {
        List<Castlight_Account__mdt> castling = [
                SELECT Plan__c, Client_ID__c, Castlight_Plan__c, DOB__c, First_Name__c, Last_Name__c, GUID__c
                FROM Castlight_Account__mdt
                WHERE Plan__c = :insurance
        ];

        return castling;
    }

    @AuraEnabled
    public static void savePatientInfo(String patientString) {
        Id userId = UserInfo.getUserId();

        PatientObject patient = (PatientObject)JSON.deserialize(patientString, PatientObject.class);

        User currentUser = new User(
                Id = userId,
                Castlight_Birthdate__c = patient.birthdate,
                Castlight_First_Name__c = patient.firstName,
                Castlight_Last_Name__c = patient.lastName,
                Castlight_Lumeris_Id__c = patient.lumerisId,
                Castlight_Client_Id__c = patient.clientId,
                FederationIdentifier = patient.insurance
        );

        update currentUser;
    }

    public class PatientObject {
        @AuraEnabled
        public String lumerisId;
        @AuraEnabled
        public String firstName;
        @AuraEnabled
        public String lastName;
        @AuraEnabled
        public String birthdate;
        @AuraEnabled
        public String insurance;
        @AuraEnabled
        public String clientId;
        @AuraEnabled
        public String error;
    }

}