src/objects/Clinic__c.object
<CustomObject>
    <description>This object will store available Clinics available for selection on Patient Referrals.</description>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <label>Clinic</label>
    <nameField>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Clinic_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Date__c</fullName>
        <label>Budget Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clinic_Name__c</fullName>
        <formula>TEXT(Clinic__r.Clinic__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clinic Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <referenceTo>Clinic__c</referenceTo>
        <relationshipLabel>Clinic Budgets</relationshipLabel>
        <relationshipName>Clinic_Budgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Clinic Budget</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinic Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinic Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Accounting_Period__c</fullName>
        <label>Accounting Period</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Schedule</label>
        <referenceTo>Revenue_Schedule__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinic__c</fullName>
        <label>Clinic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Clinics</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Schedule_Date__c</fullName>
        <label>Revenue Schedule Date</label>
        <type>Date</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GSP_SC_trgClinicBudgetMethods.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, 20 Jul 2020
 */
public with sharing class GSP_SC_trgClinicBudgetMethods
{
	public static void LinkLineItemsAndSchedules(List<Clinic_Budget__c> clinicBudgetList)
	{
		Set<Integer> monthSet = new Set<Integer>(),
			yearSet = new Set<Integer>();
		Set<String> clinicNameSet = new Set<String>();
		Set<Id> clinicBudgetSet = new Set<Id>();
		Map<String, Map<Integer, Map<Integer, Clinic_Budget__c>>> clinicBudgetSearchMap = new Map<String, Map<Integer, Map<Integer, Clinic_Budget__c>>>();
		List<Invoice_Line__c> invoiceLineCache = new List<Invoice_Line__c>();
		List<Revenue_Schedule__c> revenueScheduleCache = new List<Revenue_Schedule__c>();
		 
		for (Clinic_Budget__c clinicBudget : clinicBudgetList)
		{
			monthSet.add(clinicBudget.Budget_Date__c.month());
			yearSet.add(clinicBudget.Budget_Date__c.year());
			clinicNameSet.add(clinicBudget.Clinic_Name__c);
			
			if (!clinicBudgetSearchMap.containsKey(clinicBudget.Clinic_Name__c))
			{
				clinicBudgetSearchMap.put(clinicBudget.Clinic_Name__c, new Map<Integer, Map<Integer, Clinic_Budget__c>>());
			}
			if (!clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).containsKey(clinicBudget.Budget_Date__c.year()))
			{
				clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).put(clinicBudget.Budget_Date__c.year(), new Map<Integer, Clinic_Budget__c>()); 
			}
			clinicBudgetSearchMap.get(clinicBudget.Clinic_Name__c).get(clinicBudget.Budget_Date__c.year()).put(clinicBudget.Budget_Date__c.month(), clinicBudget);
		}
		
		for (Invoice_Line__c invoiceLine : [
			SELECT
				Id,
				Clinic__c,
				Accounting_Period__c,
				Clinic_Budget__c
			FROM
				Invoice_Line__c
			WHERE
				CALENDAR_MONTH(Accounting_Period__c) IN :monthSet
			AND
				CALENDAR_YEAR(Accounting_Period__c) IN :yearSet
			AND
				Clinic__c IN :clinicNameSet])
		{
			if (invoiceLine.Clinic_Budget__c != null)
			{
				clinicBudgetSet.add(invoiceLine.Clinic_Budget__c);
				invoiceLine.Clinic_Budget__c = null;
			}
			if (clinicBudgetSearchMap.containsKey(invoiceLine.Clinic__c))
			{
				if (clinicBudgetSearchMap.get(invoiceLine.Clinic__c).containsKey(invoiceline.Accounting_Period__c.year()))
				{
					if (clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceline.Accounting_Period__c.year()).
						containsKey(invoiceline.Accounting_Period__c.month()))
					{
						Id clinicBudgetId = clinicBudgetSearchMap.get(invoiceLine.Clinic__c).get(invoiceline.Accounting_Period__c.year()).
							get(invoiceline.Accounting_Period__c.month()).Id;
						invoiceLine.Clinic_Budget__c = clinicBudgetId;
						clinicBudgetSet.add(clinicBudgetId); 
					}
				}
			}
			invoiceLineCache.add(invoiceLine);
		}
		
		for (Revenue_Schedule__c revenueSchedule : [
			SELECT
				id,
				Revenue_Schedule_Date__c,
				Clinic__c,
				Clinic_Budget__c
			FROM
				Revenue_Schedule__c
			WHERE
				CALENDAR_MONTH(Revenue_Schedule_Date__c) IN :monthSet
			AND
				CALENDAR_YEAR(Revenue_Schedule_Date__c) IN :yearSet
			AND
				Clinic__c IN :clinicNameSet])
		{
			if (revenueSchedule.Clinic_Budget__c != null)
			{
				clinicBudgetSet.add(revenueSchedule.Clinic_Budget__c);
				revenueSchedule.Clinic_Budget__c = null;
			}
			if (clinicBudgetSearchMap.containsKey(revenueSchedule.Clinic__c))
			{
				if (clinicBudgetSearchMap.get(revenueSchedule.Clinic__c).containsKey(revenueSchedule.Revenue_Schedule_Date__c.year()))
				{
					if (clinicBudgetSearchMap.get(revenueSchedule.Clinic__c).get(revenueSchedule.Revenue_Schedule_Date__c.year()).
						containsKey(revenueSchedule.Revenue_Schedule_Date__c.month()))
					{
						Id clinicBudgetId = clinicBudgetSearchMap.get(revenueSchedule.Clinic__c).get(revenueSchedule.Revenue_Schedule_Date__c.year()).
							get(revenueSchedule.Revenue_Schedule_Date__c.month()).Id;
						revenueSchedule.Clinic_Budget__c = clinicBudgetId;
						clinicBudgetSet.add(clinicBudgetId);
					}
				}
			}
			revenueScheduleCache.add(revenueSchedule);
		}
		
		if (!invoiceLineCache.isEmpty())
		{
			update invoiceLineCache;
		}
		if (!revenueScheduleCache.isEmpty())
		{
			update revenueScheduleCache;
		}
		
		if (!clinicBudgetSet.isEmpty())
		{
			GSP_SC_ClinicBudgetHelper.RollUpClinicBudgets(clinicBudgetSet);
		}
	}
}