src/objects/Clinic_Budget__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Invoice Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pipeline_Scheduled_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Sum of related Revenue Schedules where the Opportunity is Open.</inlineHelpText>
        <label>Pipeline Scheduled Revenue</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Won_Scheduled_Revenue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Won Scheduled Revenue</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Clinic Budget</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Clinic Budget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinic Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Invoice Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Schedule</label>
        <referenceTo>Revenue_Schedule__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Power of One field For reporting</description>
        <formula>1</formula>
        <label>Opportunity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Revenue_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Clinic_Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinic Budget</label>
        <referenceTo>Clinic_Budget__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>Revenue_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revenue_Amount__c</fullName>
        <label>Revenue Amount</label>
        <precision>16</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{00000}</displayFormat>
        <label>Revenue Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GSP_SC_ClinicBudgetHelper.cls
/* Copyright (C) Gary Smith Partnership - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Gary Smith Partnership <gary@garysmithpartnership.com>, 23 Oct 2020
 */
public with sharing class GSP_SC_ClinicBudgetHelper
{
	@TestVisible
	private static Map<String, Decimal> currencyMap = new Map<String, Decimal>();
	@TestVisible
	private static Boolean bIsMulticurrency = Schema.getGlobalDescribe().containsKey('CurrencyType');
	
    public static void RollUpClinicBudgets(Set<Id> clinicBudgetSet)
    {
    	List<Clinic_Budget__c> clinicBudgetCache = new List<Clinic_Budget__c>();
		
		if (bIsMulticurrency)
		{
			String strCurrencyType = 'SELECT IsoCode, ConversionRate FROM CurrencyType';
	
			for (Sobject currencyType : Database.query(strCurrencyType))
			{
				GSP_SC_ClinicBudgetHelper.currencyMap.put(String.valueOf(currencyType.get('IsoCode')), (Decimal)(currencyType.get('ConversionRate')));
			}
		}
		
		String strSOQL = 'SELECT Id, Invoice_Amount__c, Pipeline_Scheduled_Revenue__c, Won_Scheduled_Revenue__c,';
		if (bIsMulticurrency)
		{
			strSOQL += ' CurrencyIsoCode,';
		}
		strSOQL += ' (SELECT Id, Opportunity__r.IsWon, Opportunity__r.IsClosed, Revenue_Amount__c';
		if (bIsMulticurrency)
		{
			strSOQL += ', CurrencyIsoCode';
		}
		strSOQL += ' FROM Revenue_Schedules__r), (SELECT Id, Amount__c';
		if (bIsMulticurrency)
		{
			strSOQL += ', CurrencyIsoCode';
		}
		strSOQL += ' FROM Invoice_Lines__r) FROM Clinic_Budget__c WHERE	Id IN :clinicBudgetSet';
		
    	for (Clinic_Budget__c clinicBudget : Database.query(strSOQL))
    	{
    		clinicBudget.Invoice_Amount__c =
    		clinicBudget.Pipeline_Scheduled_Revenue__c =
    		clinicBudget.Won_Scheduled_Revenue__c = 0;
    		
    		for (Revenue_Schedule__c revenueSchedule : clinicBudget.Revenue_Schedules__r)
    		{
    			if (revenueSchedule.Opportunity__r.IsWon)
    			{
    				if (bIsMulticurrency)
    				{
    					clinicBudget.Won_Scheduled_Revenue__c += revenueSchedule.Revenue_Amount__c == null ? 0 :
    						ConvertCurrency(revenueSchedule.Revenue_Amount__c, String.valueOf(revenueSchedule.get('CurrencyIsoCode')),
    						String.valueOf(clinicBudget.get('CurrencyIsoCode')));
    				}
    				else
    				{
    					clinicBudget.Won_Scheduled_Revenue__c += revenueSchedule.Revenue_Amount__c == null ? 0 : revenueSchedule.Revenue_Amount__c;
    				} 
    			}
    			else if (!revenueSchedule.Opportunity__r.IsClosed)
    			{
    				if (bIsMulticurrency)
    				{
    					clinicBudget.Pipeline_Scheduled_Revenue__c += revenueSchedule.Revenue_Amount__c == null ? 0 :
    						ConvertCurrency(revenueSchedule.Revenue_Amount__c, String.valueOf(revenueSchedule.get('CurrencyIsoCode')),
    						String.valueOf(clinicBudget.get('CurrencyIsoCode')));
    				}
    				else
    				{
    					clinicBudget.Pipeline_Scheduled_Revenue__c += revenueSchedule.Revenue_Amount__c == null ? 0 : revenueSchedule.Revenue_Amount__c;
    				} 
    			}
    		}
    		
    		for (Invoice_Line__c invoiceLine : clinicBudget.Invoice_Lines__r)
    		{
    			clinicBudget.Invoice_Amount__c += invoiceLine.Amount__c == null ? 0 : invoiceLine.Amount__c;
    		}
    		clinicBudgetCache.add(clinicBudget);
    	}
    	
    	if (!clinicBudgetCache.isEmpty())
    	{
    		update clinicBudgetCache;
    	}
    }
    
    @TestVisible
	private static Decimal ConvertCurrency(Decimal amount, String sourceCurrencyIsoCode, String targetCurrencyIsoCode)
	{
		if (amount == null)
		{
			return 0;
		}
		System.assertEquals(true, GSP_SC_ClinicBudgetHelper.currencyMap.containsKey(sourceCurrencyIsoCode));
		System.assertEquals(true, GSP_SC_ClinicBudgetHelper.currencyMap.containsKey(targetCurrencyIsoCode));
		return (amount * (GSP_SC_ClinicBudgetHelper.currencyMap.get(targetCurrencyIsoCode) /
			GSP_SC_ClinicBudgetHelper.currencyMap.get(sourceCurrencyIsoCode))).setScale(2);
	} 
}