src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lumeris_ID__c</fullName>
        <externalId>true</externalId>
        <label>Lumeris ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Use this record type for patients.</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/XO_Follow_Up_Tracking__c.object
<CustomObject>
    <description>Follow Up Tracking is the latest production object that is location (profile) specific allowing for tracking of referrals, tasks and other items that require workflow reminders.</description>
    <fields>
        <fullName>Imaging__c</fullName>
        <label>Imaging</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Reason_For_Follow_Up__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Addison Gilbert Hospital</fullName>
                </value>
                <value>
                    <fullName>ARA Diagnostic Imaging</fullName>
                </value>
                <value>
                    <fullName>Cardiografix</fullName>
                </value>
                <value>
                    <fullName>Center for Diagnostic Imaging (CDI)</fullName>
                </value>
                <value>
                    <fullName>CPMC</fullName>
                </value>
                <value>
                    <fullName>Dipa Patel, M.D.</fullName>
                </value>
                <value>
                    <fullName>Dominican Hospital</fullName>
                </value>
                <value>
                    <fullName>DRI</fullName>
                </value>
                <value>
                    <fullName>El Camino Imaging</fullName>
                </value>
                <value>
                    <fullName>Good Sam Breast Center</fullName>
                </value>
                <value>
                    <fullName>Good Sam DEXA Scan</fullName>
                </value>
                <value>
                    <fullName>Health Diagnostics</fullName>
                </value>
                <value>
                    <fullName>Imaging Austin 1</fullName>
                </value>
                <value>
                    <fullName>Imaging Austin 2</fullName>
                </value>
                <value>
                    <fullName>Insight Imaging</fullName>
                </value>
                <value>
                    <fullName>M&amp;S</fullName>
                </value>
                <value>
                    <fullName>Mammography Spec Med Corp</fullName>
                </value>
                <value>
                    <fullName>O&apos;Connor Hospital</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PAMF</fullName>
                </value>
                <value>
                    <fullName>Peninsula Diagnostics Imaging</fullName>
                </value>
                <value>
                    <fullName>SimonMed</fullName>
                </value>
                <value>
                    <fullName>Stanford Imaging Center</fullName>
                </value>
                <value>
                    <fullName>Sunnyvale Imaging Center</fullName>
                </value>
                <value>
                    <fullName>Sutter</fullName>
                </value>
                <value>
                    <fullName>UC Davis</fullName>
                </value>
                <value>
                    <fullName>UCSF</fullName>
                </value>
                <value>
                    <fullName>Valley Radiology (VRI)</fullName>
                </value>
                <value>
                    <fullName>WRI (Palo Alto Imaging)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lumeris_ID__c</fullName>
        <label>Lumeris ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_For_Follow_Up__c</fullName>
        <label>Reason For  Follow-Up</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Referral</fullName>
                </value>
                <value>
                    <fullName>Medical Specialty Referral</fullName>
                </value>
                <value>
                    <fullName>Care Coordination</fullName>
                </value>
                <value>
                    <fullName>Findrisc</fullName>
                </value>
                <value>
                    <fullName>Follow Up Office Visit</fullName>
                </value>
                <value>
                    <fullName>Imaging</fullName>
                </value>
                <value>
                    <fullName>MD Followup</fullName>
                </value>
                <value>
                    <fullName>Medical Records</fullName>
                </value>
                <value>
                    <fullName>Nurse Follow Up</fullName>
                </value>
                <value>
                    <fullName>Patient Communication</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referring_Provider__c</fullName>
        <description>Provider requesting referral</description>
        <label>Referring Provider</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abucayan Krystal</fullName>
                </value>
                <value>
                    <fullName>Ajay Gupta, MD</fullName>
                </value>
                <value>
                    <fullName>Akbar Zikria</fullName>
                </value>
                <value>
                    <fullName>Akbar Zikria, DO</fullName>
                </value>
                <value>
                    <fullName>Aki Yoshikawa, PTA</fullName>
                </value>
                <value>
                    <fullName>Alan Gjedsted, MD</fullName>
                </value>
                <value>
                    <fullName>Alexandra Garcia, MD</fullName>
                </value>
                <value>
                    <fullName>Alex Mackenzie, MFT</fullName>
                </value>
                <value>
                    <fullName>Alona Habinsky, NP</fullName>
                </value>
                <value>
                    <fullName>Amber Malik, MD</fullName>
                </value>
                <value>
                    <fullName>Ami Kadakia, MD</fullName>
                </value>
                <value>
                    <fullName>Amit Batra, MD</fullName>
                </value>
                <value>
                    <fullName>Amy Hockenbrock, MD</fullName>
                </value>
                <value>
                    <fullName>Amy Spaar, RN</fullName>
                </value>
                <value>
                    <fullName>Anahita Forati, LAc</fullName>
                </value>
                <value>
                    <fullName>Anand Singh, MD</fullName>
                </value>
                <value>
                    <fullName>Andrea Sullivan, MD</fullName>
                </value>
                <value>
                    <fullName>Angela Stanford, RD</fullName>
                </value>
                <value>
                    <fullName>Anita Gaind, MD</fullName>
                </value>
                <value>
                    <fullName>Annie Low, OD</fullName>
                </value>
                <value>
                    <fullName>Ann Messer MD</fullName>
                </value>
                <value>
                    <fullName>Asha Alex, MD</fullName>
                </value>
                <value>
                    <fullName>Ashley Maltz MD</fullName>
                </value>
                <value>
                    <fullName>Asiya Khan, MD</fullName>
                </value>
                <value>
                    <fullName>Barbara Campbell, MD</fullName>
                </value>
                <value>
                    <fullName>Barry Giglio, MD</fullName>
                </value>
                <value>
                    <fullName>Becky Guarino, MD</fullName>
                </value>
                <value>
                    <fullName>Becky Schmitz, MD</fullName>
                </value>
                <value>
                    <fullName>Bias Travis</fullName>
                </value>
                <value>
                    <fullName>Blakely Richardson, DO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>XO Follow Up Tracking</label>
    <nameField>
        <label>Patient Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>XO Follow Up Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testSavePatientAndXOFollowController.cls
@isTest
public class testSavePatientAndXOFollowController
{
    @isTest
    static void testController()
    {
        String xoRTypeId = '';
        List<RecordType> rtypes = [select Id, Name from RecordType where SobjectType='XO_Follow_Up_Tracking__c'];
        if(rtypes.size() > 0)
        {
            xoRTypeId = rtypes[0].Id;           
        }
        recordtype patientcntrt = [select Id from Recordtype where name = 'patient' and sobjecttype = 'contact'];
        Contact testPatient = new COntact(recordtypeid = patientcntrt.Id, Email = 'test@test.com', Lumeris_ID__c = '123edswa', firstname = 'david', lastname = 'lee', Phone = '2345643');
        insert testPatient;
        PageReference retPage = new PageReference('/apex/SavePatientAndXOFollow?RecordType=' + xoRTypeId);
        test.setCurrentPage(retPage);
        SavePatientAndXOFollowController controller = new SavePatientAndXOFollowController();
        system.assert(controller.AllXOTrackRecordsTyes != null);
        controller.DOB = '09/23/2015';
        controller.ScheudleFollowUpDate =  '09/23/2015';
        controller.Patientcnt = testPatient;
        controller.XOFollowUpTracking.Reason_For_Follow_Up__c = 'Imaging';
        controller.XOFollowUpTracking.Imaging__c = 'Cardiografix';
        controller.XOFollowUpTracking.Referring_Provider__c = 'Andrea Sullivan, MD';
        SavePatientAndXOFollowController.searchPatient('Da');
        controller.save();
        controller.cancel();
    }
    @isTest
    static void testController2()
    {
        String xoRTypeId = '';
        List<RecordType> rtypes = [select Id, Name from RecordType where SobjectType='XO_Follow_Up_Tracking__c'];
        if(rtypes.size() > 0)
        {
            xoRTypeId = rtypes[0].Id;           
        }
        recordtype patientcntrt = [select Id from Recordtype where name = 'patient' and sobjecttype = 'contact'];
        Contact testPatient = new COntact(recordtypeid = patientcntrt.Id, Email = 'test@test.com', Lumeris_ID__c = '123edswa', firstname = 'david', lastname = 'lee', Phone = '2345643');
        insert testPatient;
        PageReference retPage = new PageReference('/apex/SavePatientAndXOFollow?RecordType=' + xoRTypeId);
        test.setCurrentPage(retPage);
        SavePatientAndXOFollowController controller = new SavePatientAndXOFollowController();
        system.assert(controller.AllXOTrackRecordsTyes != null);
        controller.DOB = '09/23/2015';
        controller.ScheudleFollowUpDate =  '09/23/2015';
        controller.Patientcnt = testPatient;
        controller.saveAndNew();
    }
    
    @isTest
    static void testController3()
    {
        String xoRTypeId = '';
        List<RecordType> rtypes = [select Id, Name from RecordType where SobjectType='XO_Follow_Up_Tracking__c'];
        if(rtypes.size() > 0)
        {
            xoRTypeId = rtypes[0].Id;           
        }
        recordtype patientcntrt = [select Id from Recordtype where name = 'patient' and sobjecttype = 'contact'];
        Contact testPatient = new COntact(recordtypeid = patientcntrt.Id, Email = 'test@test.com', Lumeris_ID__c = '123edswa', firstname = 'david', lastname = 'lee', Phone = '2345643');
        insert testPatient;
        PageReference retPage = new PageReference('/apex/SavePatientAndXOFollow?RecordType=' + xoRTypeId);
        test.setCurrentPage(retPage);
        XO_Follow_Up_Tracking__c xo = new XO_Follow_Up_Tracking__c();
        ApexPages.StandardController stdController = new ApexPages.StandardController(xo);
        SavePatientAndXOFollowController controller = new SavePatientAndXOFollowController(stdController);
        system.assert(controller.AllXOTrackRecordsTyes != null);
        controller.DOB = '09/23/2015';
        controller.ScheudleFollowUpDate =  '09/23/2015';
        controller.Patientcnt = testPatient;
        controller.saveAndNew();
    }
    
    @isTest
    static void testController4()
    {
        String xoRTypeId = '';
        List<RecordType> rtypes = [select Id, Name from RecordType where SobjectType='XO_Follow_Up_Tracking__c'];
        if(rtypes.size() > 0)
        {
            xoRTypeId = rtypes[0].Id;           
        }
        recordtype patientcntrt = [select Id from Recordtype where name = 'patient' and sobjecttype = 'contact'];
        Contact testPatient = new COntact(recordtypeid = patientcntrt.Id, Email = 'test@test.com', Lumeris_ID__c = '123edswa', firstname = 'david', lastname = 'lee', Phone = '2345643');
        insert testPatient;
        PageReference retPage = new PageReference('/apex/SavePatientAndXOFollow');
        test.setCurrentPage(retPage);
        XO_Follow_Up_Tracking__c xo = new XO_Follow_Up_Tracking__c();
        ApexPages.StandardController stdController = new ApexPages.StandardController(xo);
        SavePatientAndXOFollowController controller = new SavePatientAndXOFollowController(stdController);
        system.assert(controller.AllXOTrackRecordsTyes != null);
        controller.DOB = '09/23/2015';
        controller.ScheudleFollowUpDate =  '09/23/2015';
        controller.Patientcnt = testPatient;
        controller.XOFollowUpTracking.Reason_For_Follow_Up__c = 'Imaging';
        controller.XOFollowUpTracking.Imaging__c = 'Cardiografix';
        controller.XOFollowUpTracking.Referring_Provider__c = 'Andrea Sullivan, MD';
        SavePatientAndXOFollowController.searchPatient('Da');
        controller.save();
        controller.cancel();
    }
}