src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EMR__c</fullName>
        <description>Unique patient EMR identifier in Elation. Requested by Sarah L for Patient Referral Management project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Enter the unique EMR associated with this Contact.</inlineHelpText>
        <label>EMR</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Use this record type for patients.</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Used to capture XO Patients</description>
    <label>Patient</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Patient Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Referral__c.object
<CustomObject>
    <description>This object will store the Patient Referrals beign managed.</description>
    <fields>
        <fullName>EMR__c</fullName>
        <description>Displays the value of the Patient__r.EMR__c field on the selected Patient Contact record. Requested by Sarah L for Patient Referral Management project.</description>
        <formula>Patient__r.EMR__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMR</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Patient Contact associated with the Patient Referral. Requested by Sarah L for Patient Referral Management project.</description>
        <inlineHelpText>Select the Patient Contact associated with this Patient Referral.</inlineHelpText>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Patient Referrals</relationshipLabel>
        <relationshipName>Patient_Referrals</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specialist__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Specialist referred for the Patient Referral. Requested by Sarah L for Patient Referral Management project.</description>
        <inlineHelpText>Select the Specialist referred for this Patient Referral.</inlineHelpText>
        <label>Specialist</label>
        <referenceTo>Specialist__c</referenceTo>
        <relationshipLabel>Patient Referrals</relationshipLabel>
        <relationshipName>Patient_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Specialty_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Detail__c</fullName>
        <label>Status Detail</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Cost</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>No Report Received- No Survey Sent</fullName>
                </value>
                <value>
                    <fullName>No Report Received- Survey Sent</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Referral Options Provided</fullName>
                </value>
                <value>
                    <fullName>Ref Receipt - Established Care</fullName>
                </value>
                <value>
                    <fullName>Report Received - No Survey Sent</fullName>
                </value>
                <value>
                    <fullName>Report Received - Survey Sent</fullName>
                </value>
                <value>
                    <fullName>Report Requested</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Unhappy - Reroute</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Unscheduled</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                    <isActive>false</isActive>
                    <label>Duplicate</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                    <isActive>false</isActive>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>Incorrect</fullName>
                    <isActive>false</isActive>
                    <label>Incorrect</label>
                </value>
                <value>
                    <fullName>No Notes</fullName>
                    <isActive>false</isActive>
                    <label>No Notes</label>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                    <isActive>false</isActive>
                    <label>Patient Declined</label>
                </value>
                <value>
                    <fullName>Pending Additional Notes</fullName>
                    <isActive>false</isActive>
                    <label>Pending Additional Notes</label>
                </value>
                <value>
                    <fullName>Pending Location Preference</fullName>
                    <isActive>false</isActive>
                    <label>Pending Location Preference</label>
                </value>
                <value>
                    <fullName>Pending Provider Instruction</fullName>
                    <isActive>false</isActive>
                    <label>Pending Provider Instruction</label>
                </value>
                <value>
                    <fullName>Reroute</fullName>
                    <isActive>false</isActive>
                    <label>Reroute</label>
                </value>
                <value>
                    <fullName>Scheduled w/ Different Specialist</fullName>
                    <isActive>false</isActive>
                    <label>Scheduled w/ Different Specialist</label>
                </value>
                <value>
                    <fullName>Unresponvie</fullName>
                    <isActive>false</isActive>
                    <label>Unresponvie</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XO_Internal_Rating__c</fullName>
        <label>XO Internal Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XO_Provider_Rating__c</fullName>
        <inlineHelpText>XO Provider Rating on a scale of 1 - 5 stars.</inlineHelpText>
        <label>XO Provider Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient Referral</label>
    <nameField>
        <displayFormat>XOPR-{0000}</displayFormat>
        <label>Patient Referral ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Specialist__c.object
<CustomObject>
    <description>This object will store available Specialists available for selection on Patient Referrals.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Specialty_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Specialist</label>
    <nameField>
        <label>Specialist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Specialty__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quality_Score__c</fullName>
        <label>Quality Score</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialist__c</fullName>
        <label>Specialist</label>
        <referenceTo>Specialist__c</referenceTo>
        <relationshipLabel>Specialties</relationshipLabel>
        <relationshipName>Specialties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>XO_Internal_Rating__c</fullName>
        <inlineHelpText>Rate the provider on a scale of 1 - 5 based on the ease of scheduling, response time, etc.</inlineHelpText>
        <label>XO Internal Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>XO_Provider_Rating__c</fullName>
        <label>XO Provider Rating</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Specialty</label>
    <nameField>
        <label>Specialty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specialties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SpecialistsTableControllerTest.cls
/**
 * Created by Pavel Kovalevsky on 11/12/2020.
 */
@isTest
private class SpecialistsTableControllerTest {

    private static Patient_Referral__c currentRecord;
    private static Specialist__c specialist;

    private static void init() {
        Id rtId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Patient').getRecordTypeId();

        Contact patient = new Contact(LastName = 'Test', MailingStreet = '235 Morse Rd', MailingCity = 'Portland', MailingPostalCode = '72206',
        MailingCountry = 'United States', MailingLatitude = 34.672, MailingLongitude = -92.2682, EMR__c = 'emr', RecordTypeId = rtId);
        insert patient;

        currentRecord = new Patient_Referral__c(Patient__c = patient.Id, Specialty__c = 'Audiology', Status_Detail__c = 'Pending');
        insert currentRecord;

        specialist = new Specialist__c(Name = 'Specialist', Specialty__c = 'Audiology', Country__c = 'United States', City__c = 'Portland',
            Street__c = '235 Morse Rd', Zip__c = '72206');
        insert specialist;

        Specialty__c specialty = new Specialty__c(Specialist__c = specialist.Id, Name = 'Specialty', Cost__c = 15, Quality_Score__c = '1', XO_Internal_Rating__c = '1',
            XO_Provider_Rating__c = '2');
        insert specialty;
    }

    @isTest static void test_getInitialInfo() {
        init();
        Test.startTest();
        System.assertEquals(SpecialistsTableController.getInitialInfo(currentRecord.Id).size(), 1);
        Test.stopTest();
    }

    @isTest static void test_getFilteredRecords() {
        init();
        Test.startTest();
        System.assertEquals(SpecialistsTableController.getFilteredRecords(currentRecord.Id, '72206', 'Portland', 'Audiology').size(), 1);
        Test.stopTest();
    }

    @isTest static void test_updatePatientReferral() {
        init();
        specialist.Name = 'UpdatedName';
        update specialist;

        Test.startTest();
        SpecialistsTableController.updatePatientReferral(currentRecord.Id, specialist.Id, 1, 2, 3, 4, null);
        Test.stopTest();

        List<Patient_Referral__c> checkRef = [SELECT XO_Internal_Rating__c FROM Patient_Referral__c];
        System.assertEquals(checkRef.get(0).XO_Internal_Rating__c, '3');
    }

}