src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Use this record type for patients.</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient__c.object
<CustomObject>
    <description>Used to capture XO Patients</description>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_First_Name__c</fullName>
        <label>Patient First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Last_Name__c</fullName>
        <label>Patient Last Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Patient Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SearchProviderControllerTest.cls
@IsTest
private class SearchProviderControllerTest {

    @IsTest
    static void testGetPatient() {
        Account acc = new Account(
                Name = 'Test'
        );
        insert acc;

        Contact con = new Contact(
                AccountId = acc.Id,
                LastName = 'Test',
                Insurance__c = 'Premera Health Savings Plan'
        );
        insert con;

        SearchProviderController.PatientObject patient = SearchProviderController.getPatient(con.Id);
        String patientString = JSON.serialize(patient);
        SearchProviderController.savePatientInfo(patientString);
    }

    @IsTest
    static void testGetPatientForPatient() {
        Patient__c pat = new Patient__c(
                Patient_First_Name__c = 'Test',
                Patient_Last_Name__c = 'Test',
                Insurance__c = 'Premera Health Savings Plan'
        );
        insert pat;

        SearchProviderController.PatientObject patient = SearchProviderController.getPatient(pat.Id);
        String patientString = JSON.serialize(patient);
        SearchProviderController.savePatientInfo(patientString);
    }
}